### ISSUE TITLE
[Feature request] Select first element by pressing 'enter' key 

### ISSUE THREAD

**Issue by 76200** [LeaVerou/awesomplete#1]
Right now I have to press "down arrow" key and then "enter" to select first element. It would be great to press just one key, especially when there's only one element left in the list.

Using http://leaverou.github.io/awesomplete/ example: 
Type "js", hit "enter" and get "Node.js"

**Comment by tporadowski** [comment]
@76200 there is an option `autoFirst` (`data-autofirst` attribute) that does so

**Comment by 76200** [comment]
@tporadowski right ;)

**Comment by LeaVerou** [comment]
Yup, use `data-autofirst` (or the JS property `autoFirst`). :)
The idea is that this behavior is desirable in cases where the majority of input will come from the popup, but not when the popup is merely suggestions and the majority of input will come from freeform text.
My estimate is that the latter is more common than the former, so the default of `autoFirst` was chosen to be `false`.
