### ISSUE TITLE
add accessibility support

### ISSUE THREAD

**Issue by ginader** [LeaVerou/awesomplete#10]
Hi Lea,
I think you did some great work to make it look and feel like a really nice autocomplete widget. Now let's also make it accessible to users of assistive technologies (i.e. Screenreaders).
As it turns out the jQuery UI autocomplete is a really good example (the Paciello Group worked on making jQuery UI accessible).
If you install i.e. Chromevox and use the jQuery example here: http://jqueryui.com/autocomplete/ and your example you will notice that the jQuery Example nicely announces "10 results are available, use up and down arrow keys to navigate." in an aria-live region. And then, when using the cursor keys it updates the content of the input field which causes the selection to be read.

Here's a couple of nice resources on the topic:
https://webaccessibility.withgoogle.com/unit?unit=6&lesson=13
http://www.w3.org/TR/wai-aria/states_and_properties#aria-autocomplete

Let me know if you need help implementing this :-)

**Comment by LeaVerou** [comment]
Thanks Dirk! I will look into these resources when I get a bit of time, but PRs are very appreciated! I care a lot about making this accessible (hence my clumsy use of aria too).

**Comment by LeaVerou** [comment]
Closing issue, since PR is now merged.

**Comment by ginader** [comment]
Great! thanks :-)

**Comment by rikschennink** [comment]
I notice that VoiceOver does not communicate the "amount of results and up / down arrow tip". Is this correct and does VoiceOver just not support this functionality? Or am I missing something (tested on http://leaverou.github.io/awesomplete/ with Safari 9.1.2)
