### ISSUE TITLE
Apply same list to multiple inputs

### ISSUE THREAD

**Issue by csm123** [LeaVerou/awesomplete#1029]
Is there a recommended way to apply the same list to multiple inputs, while being as memory-efficient as possible?

**Comment by LeaVerou** [comment]
Good question! I believe setting `list` to the same array should work, but I haven’t checked.

**Comment by coRz** [comment]
It will work just assign a global array and pass it on to every autocomplete input.

**Comment by coRz** [comment]
You already have this:

```
new Awesomplete(input, {
    list: /* global array or something.. */
});
```

**Comment by csm123** [comment]
Thanks!
