### ISSUE TITLE
Needs a readme

### ISSUE THREAD

**Issue by knownasilya** [LeaVerou/awesomplete#12]
:+1:

**Comment by LeaVerou** [comment]
Why, is the website not sufficient?

**Comment by knownasilya** [comment]
The website is definitely nice, but at a quick glance, it's nice to see what it is, and how to get it.

Even if you just have a title and the link to the site, it just gives a better impression.

**Comment by viktorstrate** [comment]
Agree with you @knownasilya

**Comment by arthurvr** [comment]
Jup. The readme shouldn't contain the same content as the website has, btw. It should just have a quick intro (maybe a screenshot) and information on how to contribute.

**Comment by LeaVerou** [comment]
Guys, if somebody sends a PR for a readme, I’ll merge it :)

**Comment by neems** [comment]
I sent a PR for a readme for you from stuff on your site. :) Cool stuff you made here!
