### ISSUE TITLE
Mention License in project homepage?

### ISSUE THREAD

**Issue by danbri** [LeaVerou/awesomplete#13]
Could you add a link/mention of the license https://github.com/LeaVerou/awesomplete/blob/gh-pages/LICENSE into the homepage http://leaverou.github.io/awesomplete/#download ? 

Maybe here? https://github.com/LeaVerou/awesomplete/blob/gh-pages/index.html#L312

**Comment by LeaVerou** [comment]
Is there a reason for it? I believe it’s standard practice these days to look in the repo for a LICENSE file, or the header of the JS file…

**Comment by danbri** [comment]
I've known people especially working in big companies to be particularly jumpy about licenses - e.g.. not wanting to download/unzip a distribution to look inside in case they find the wrong flavour of GPL or whatever on the inside. But in general the Web page provides enough information for people to get up-and-running without diving into Github, I thought a quick link would save people hunting around.

**Comment by LeaVerou** [comment]
Well, I wouldn’t object to a pull request :)
