### ISSUE TITLE
Autocomplete multiple words?

### ISSUE THREAD

**Issue by nodiscc** [LeaVerou/awesomplete#14184]
Hi, thanks for your work on this. I was considering using awesomplete in https://github.com/shaarli/Shaarli, to provide autocompletion for a link "tagging" field. (We use JqueryUI for this and would like to get rid of it.)

![autcomplete](https://cloud.githubusercontent.com/assets/3950390/6425573/ba5e4ba8-bf2f-11e4-8884-5ffe256c3bff.png)

As shown on the example, a link can have multiple tags - we suggest already-existing tags on user input; every time the separating character (space) is entered, we start suggesting again for the next word. Currently awesomplete olny enables suggestions for the first word entered. How can I make awesomplete show suggestions for each word in the text input box?

**Comment by LeaVerou** [comment]
This is related to #14491 but different, in the sense that the tags are all in the input. It’s probably doable via the API in a similar way as the email domain autocomplete. I would love to work on this when I get some time.

**Comment by LeaVerou** [comment]
Actually, I thought it was too interesting and I quickly coded up an example. Check out http://leaverou.github.io/awesomplete/#multiple-values
It’s not perfect, but hopefully it’s a start :)

**Comment by nodiscc** [comment]
@LeaVerou Thanks for the quick reply, this is actually very close to what we need! We'll try to implement it as a prototype, as far as I can see it only misses 1) Using space as the separator but I guess this is a 1-char change in the example code; 2) being able to use TAB (instead of click) to trigger autocompletion for the current word, while the text area retains focus.

If you have ideas on how to achieve this they're very welcome. Thanks again!

**Comment by nodiscc** [comment]
By the way the `#multiple-values` link doesn't point to the right header. The closer I could find is https://leaverou.github.io/awesomplete/#advanced-examples

**Comment by nodiscc** [comment]
I think this can be closed, it works as expected (changing separator character is another issue, I'll have a look). Thx
