### ISSUE TITLE
Proposal: Tests

### ISSUE THREAD

**Issue by vlazar** [LeaVerou/awesomplete#14565]
Do you have plans to cover code with tests?

It seems reasonable to introduce tests for such a popular project ;)

If you are interested, I'd like to know your preferences in test/mock framework, test runner, etc. Continuous Integration would be also nice to have, as well as versioning and other staff.

But let's just start small. So... tests, YES or NO?

**Comment by LeaVerou** [comment]
Tests would be nice, don’t really have a preferred framework, I didn’t like anything I’ve tried. :/ 
In general, the simpler and easier for new contributors, the better.

**Comment by arthurvr** [comment]
Sure! :+1:

**Comment by michaelachrisco** [comment]
Ive used http://qunitjs.com/ in the past. Its pretty straight forward. We could (all)? do some collab sometime. At the very least, it will enable future pull requests to be tested.

**Comment by LeaVerou** [comment]
Oh I forgot to say: I would prefer something as popular as possible, as it increases chances that contributors will already be familiar with it.

**Comment by arthurvr** [comment]
I'm personally +1 to QUnit.

**Comment by vlazar** [comment]
Here's some popular options sorted by number of stars on github:

Testing Frameworks
https://github.com/jasmine/jasmine
https://github.com/mochajs/mocha maybe with https://github.com/chaijs/chai
https://github.com/jquery/qunit

Test Runners
https://github.com/karma-runner/karma
https://github.com/airportyh/testem

**Comment by LeaVerou** [comment]
I haven’t used them extensively, so whatever the majority goes with, I’m fine with it.
Ideally something which makes it super easy for new contributors to set it up and/or write new tests.

**Comment by juanto121** [comment]
While trying jasmine framework, which I found to have nicer syntax than qUnit and not to forget its ease of use, wondered into the problem of testing the Awesomplete private functions, are they testable? 
I couldnt come up with any way of easily testing them.

**Comment by vlazar** [comment]
So test framework is selected. Excellent!

Here is a better way to run tests with Karma test runner #16734
It would be so much easier to do TDD/BDD and we can later run tests on Travis CI.

**Comment by juanto121** [comment]
There's still discussion about the merged framework #16640. I tried to refactor the code style a bit in feace11ae43a631703dfa59a4a3276b2914c60ae but we should all agree on keeping Jasmine(or changing it) before adding coverage and automation.

**Comment by vlazar** [comment]
Ok, I think it will be easier to say if the tests are easy or not, when you see them.

As I'm more into Jasmine, I've started adding more Jasmine specs based on already merged work and @juanto121 current work in https://github.com/LeaVerou/awesomplete/commit/feace11ae43a631703dfa59a4a3276b2914c60ae . 
I'm also using Karma test runner from #16734.

@LeaVerou Can you please look at #16734 and decide if you like to use it?

**Comment by vlazar** [comment]
Closing this, since we're not only have tests now, but running them on TravisCI with Karma. Also #16785 (hopefully to be merged soon) adds nearly 100% test coverage.
