### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by constantx** [LeaVerou/awesomplete#14570]

**Comment by LeaVerou** [comment]
Sure. How?

**Comment by constantx** [comment]
- [ ] make awesomeplete awesomer as a commonJ-compatible
- [ ] install npm (part of node or https://github.com/npm/npm)
- [ ] [Getting Started with NPM (as a developer)](https://gist.github.com/coolaj86/1318304)
- [ ] :beers:

**Comment by arthurvr** [comment]
I remember I said I was going to PR this, but forgot about it. Sorry! I'll do it this evening.

**Comment by arthurvr** [comment]
@LeaVerou The package.json is fine these days, but you'll still need to publish it.

**Comment by jfeltesse** [comment]
for those stumbling on this issue, here's the command to install the package in its current state:

```
npm install "LeaVerou/awesomplete#gh-pages" --save
```

I thought I'd save people the few mins search time I just spent

**Comment by g00fy-** [comment]
+1

**Comment by Nexi** [comment]
+1

**Comment by mrblackus** [comment]
+1 for publishing on npm
Thanks @robotvert, your workaround works like a charm.

**Comment by vlazar** [comment]
We have 1.1 now https://www.npmjs.com/package/awesomplete
