### ISSUE TITLE
List of programming language does not only contain programming languages

### ISSUE THREAD

**Issue by prrrnd** [LeaVerou/awesomplete#16]
The list I am talking about is [here](http://leaverou.github.io/awesomplete/)
Ruby on Rails, for instance, is a framework. But ruby is a programming language.
I understand that the list is only there for the purpose of the demo, and that this is not a real issue, but I just think it would be good to fix it.

**Comment by bgammill** [comment]
I came here to submit a PR about that. Glad I'm not the only one that noticed that.

**Comment by arthurvr** [comment]
https://github.com/LeaVerou/awesomplete/commit/718adf1d1ffb5b47589eb86bba4574a7f872424a#commitcomment-9820079

**Comment by prrrnd** [comment]
Oh well, if the author doesn't even care.. :rocket:

**Comment by Flygenring** [comment]
Please, people!

It's like discussing if 'Fiat' belongs in a list of cars when it's a brand or that a bike shed can't be colored black because black is not actually a color...

**Comment by bgammill** [comment]
You could argue that ad naseum, but we were just trying to give a little help with consistency. It's a community for a reason. There are pull requests for a reason. There are issues for a reason.

**Comment by LeaVerou** [comment]
/me rolls eyes
This kind of OCD-like behavior also reminds me of [Well, Actually](http://tirania.org/blog/archive/2011/Feb-17.html).
I completely agree with @Flygenring. It’s a demo. It’s purpose is not to teach what programming languages are, but to offer varied examples of strings.
However if it bothers you that much, I wouldn’t object to a PR that changes the “Pick a programming language” label to something that also encompasses frameworks as well. Perhaps “What do you code in?” or something.

**Comment by schmurfy** [comment]
I can understand that you don't care about what is written in your example, fine, but why reject a pull request for it for those it bothers ?

You don't care that's fine but things like having ruby on rails categorized as a language is a common and annoying misconception and the fact you made it might just be a hint.

Your library looks nice anyway ;)

**Comment by Flygenring** [comment]
If the case is that pedantics ruins an example of how to use something (awesome), then I'd suggest to just change the label from "Pick a programming language" to "Pick a computer related term" or even "Pick a sample string" –

**Comment by Flygenring** [comment]
If the case is that pedantics ruins an example of how to use something (awesome), then I'd suggest to just change the label from "Pick a programming language" to "Pick a computer related term" or even "Pick a sample string from the list I chose" – just to make it a catch-all of sorts :)
