### ISSUE TITLE
Options to Search "Hidden" Values

### ISSUE THREAD

**Issue by ubergraham** [LeaVerou/awesomplete#16436]
Would love an option to have the search include values that might not be displayed -- for example, if you have the word Kansas, typing "KS" would still bring up Kansas. 

<option terms="KS, The Land of Oz">Kansas</option>

**Comment by LeaVerou** [comment]
I like this!

(also related to https://github.com/LeaVerou/awesomplete/issues/593 )

**Comment by vlazar** [comment]
**To everyone interested in differentiating value from displayed text, aka key/value feature, aka array of objects feature.**

The code is ready and it's almost 100% backward compatible. To ensure everything working fine for you we need your help with testing it in the wild before it's released. See this PR: [Separate label/value for each suggestion in list](https://github.com/LeaVerou/awesomplete/pull/16852)

**Comment by vlazar** [comment]
Separate `label/value` is landed #16866
It is also possible to initialize list with separate `label/value` via `<datalist>` or `<ul>`.

Read about different `label` and `value` at the end of [Basic usage](http://leaverou.github.io/awesomplete/#basic-usage) section and about new `data` method at the end of [Extend](http://leaverou.github.io/awesomplete/#extensibility) section.

You can use suggestion objects with `label/value` and have as many additional properties as you like. Changing `filter` to filter by additional hidden properties is trivial.
