### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by nodiscc** [LeaVerou/awesomplete#16642]
Currently, to add the first suggestion in the dropdown list to the input field, you have to press down arrow to select it, then enter to add the selection to the input field. Could this be done by just hitting the `Tab` key (Tab completion like in shells, IDEs...)?

**Comment by LeaVerou** [comment]
There are usability issues with this that have been discussed here: https://github.com/LeaVerou/awesomplete/pull/15170
