### ISSUE TITLE
Allow user to pull tags from the list or create new ones

### ISSUE THREAD

**Issue by campgurus** [LeaVerou/awesomplete#16641]
Not sure if this is possible with the current plugin, but I would love to use this with e.g. acts_as_taggable_on, tagging the instance object with existing tags or new ones that the user can create on the fly.

**Comment by LeaVerou** [comment]
If you describe how the interaction should work, I could look into how this would be implemented. As it currently stands, this is too high level, i.e. I’m not quite sure what you mean.
