### ISSUE TITLE
Touch on completion list not firing on iOS

### ISSUE THREAD

**Issue by stefanjudis** [LeaVerou/awesomplete#16712]
Hey Lea,

I just put awesomplete in a site I'm developing atm. Unfortunately touch on the auto completion list is not filling the input field.

Wouldn't make changing the `mousedown` handler to "normal" `click` do the job also?

```
    // change this to click
    $.bind(this.ul, {"mousedown": function(evt) {
        var li = evt.target;

        if (li !== this) {

            while (li && !/li/i.test(li.nodeName)) {
                li = li.parentNode;
            }

            if (li) {
                me.select(li);
            }
        }
    }});
```

Thanks for the nice project.

**Comment by claudioc** [comment]
Yes, I have the same issue and "click" fixes it. Thanks

**Comment by MHanslo** [comment]
I can confirm this is also an issue on our app with users reporting issues selecting the options on iPhone 6. I noticed there is a [closed PR](https://github.com/LeaVerou/awesomplete/pull/16715) that may have fixed this.

I would like to see this resolved.

**Comment by LeaVerou** [comment]
The PR is not closed, but it does have merge conflicts. If you want to help, you can try it out and see if the issue is resolved and whether it causes any regressions in other browsers.

**Comment by Narretz** [comment]
I just tested this on an iphone 5 with ios 10, and everything works as expected. Can somebody confirm this? Maybe Apple actually fixed a bug for once.

**Comment by Narretz** [comment]
@MHanslo @stefanjudis @claudioc if you have time (and still use this plugin), can you test the patch in https://github.com/LeaVerou/awesomplete/issues/17006?
