### ISSUE TITLE
[Feature Request] Force autocomplete="off" by default

### ISSUE THREAD

**Issue by thdoan** [LeaVerou/awesomplete#16714]
In Chrome, the native autocomplete dropdown is conflicting with the Awesomplete overlay. To prevent this, Awesomplete should add autocomplete="off" to the input element by default instead of requiring the user to do so manually.

**Comment by LeaVerou** [comment]
Are you using the latest version? I remember merging a pull request about this.

**Comment by thdoan** [comment]
Yes, I just downloaded it yesterday from http://leaverou.github.io/awesomplete/#download.

**Comment by LeaVerou** [comment]
I just checked and it does indeed turn autocomplete off, see: https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L16
You can test in the homepage that it does, indeed, add autocomplete="off" to all awesompleted inputs. Could something in your code be conflicting with this?

**Comment by thdoan** [comment]
Hi, I think I know what the issue is: when I downloaded your zip I used the minified version, and it appears that awesomplete.min.js does not contain the merged code to set autocomplete="off". Here is the pertinent section of the minified code:

```
this.input=d(a);this.input.setAttribute("aria-autocomplete","list");b=b||{};
```

It is missing this line:

```
this.input.setAttribute("autocomplete", "off");
```

**Comment by thdoan** [comment]
UPDATE: I just grabbed a new copy of your zip and I can see that the minified version also has the merged code, so I probably just downloaded the zip _right_ before it was updated :-). Closing...
