### ISSUE TITLE
Mobile text color on list

### ISSUE THREAD

**Issue by manattweb** [LeaVerou/awesomplete#16735]
I'm having an issue where the autocomplete text list is white on a white background. Is there a CSS style I can modify to fix this? Attached is an image example.
![autocompleteissue](https://cloud.githubusercontent.com/assets/3402707/7643342/4e7bfe0c-fa5e-11e4-8967-660f98f68cfc.PNG)

**Comment by manattweb** [comment]
I think I figured it out. Added a color to div.awesomplete > ul below the call to the included CSS file.

**Comment by erquhart** [comment]
@manattweb if this is resolved you should close 'er out.

**Comment by manattweb** [comment]
Well...it's only resolved because I made a custom CSS class. Has this been addressed in the core product?

**Comment by erquhart** [comment]
Probably not a product issue, as you would expect to override default styles with your own styles, just as you've done.

**Comment by manattweb** [comment]
If you say so, white text on a white background seems to be a poor choice for default styles.

**Comment by erquhart** [comment]
I'm not a core contributor or anything, so by all means, leave it open if you disagree.

That said, the default isn't white on white, it's black on white:
![awesomplete-color](https://cloud.githubusercontent.com/assets/2112202/8275714/7076a474-1879-11e5-9e2d-a3486786dc56.png)

Awesomplete default styles are probably being overridden by something on your site.
