### ISSUE TITLE
Multiple values

### ISSUE THREAD

**Issue by Cathbar2** [LeaVerou/awesomplete#16748]
Hello,

How can I use multiple values with this list ? :

> ```
> <input class="awesomplete" list="mylist" />
> <datalist id="mylist">
>     <option>Ada</option>
>     <option>Java</option>
>     <option>JavaScript</option>
>     <option>Brainfuck</option>
>     <option>LOLCODE</option>
>     <option>Node.js</option>
>     <option>Ruby on Rails</option>
> </datalist>
> ```

I try to change 

```
<datalist id="mylist">  to <datalist id="mylist" data-multiple>
```

An change the js fonction like this 

```
new Awesomplete($('datalist[data-multiple]')
```

but it doesn't work..
I need some help pls

**Comment by vlazar** [comment]
For reference #16799#issuecomment-170210544
