### ISSUE TITLE
Multiple values improvements

### ISSUE THREAD

**Issue by ArthurHoaro** [LeaVerou/awesomplete#16749]
After #14184, we've switch to awesomplete, and are happy about it. Thanks for your work.

After using the multiple values feature for a while there are two improvements which can be done:
- matching characters are only highlighted for the first word:

![2015-07-08 12_45_19-mwarfff](https://cloud.githubusercontent.com/assets/1962678/8568608/7f862810-256f-11e5-8ab5-893c304ae0a0.png)

![2015-07-08 12_45_42-mwarfff](https://cloud.githubusercontent.com/assets/1962678/8568610/81c4a912-256f-11e5-9817-eab925173916.png)
- Hide already chosen elements. Example: in the second screenshot, `opensource` shouldn't be proposed.

I've done an ugly workaround to prevent this here: [L56](https://github.com/ArthurHoaro/Shaarli/commit/3d3692bc24aa3cf68c599706f5638e690b935b3f#diff-a935381fb9fd452471c487313970965dR56)

**Comment by vlazar** [comment]
@ArthurHoaro I've splitted this issue into #16814 and #16815 and closing this issue. Please track mentioned issue instead.
