### ISSUE TITLE
Need for a first release tag

### ISSUE THREAD

**Issue by bcopy** [LeaVerou/awesomplete#16747]
Hi,

I've requested a Webjar packaging of awesomplete, but I couldn't refer to a GIT tag - please produce one. That would help with following up on the code.

Best regards,

Brice

**Comment by vlazar** [comment]
Closing, as [1.0.0](https://github.com/LeaVerou/awesomplete/releases) was tagged and awesomplete is on Webjar now https://github.com/webjars/awesomplete
