### ISSUE TITLE
can't find it with bower and a problem

### ISSUE THREAD

**Issue by haheute** [LeaVerou/awesomplete#16757]
When I `bower search awesomplete` I don't find this original awesomplete, but these two:

```
rbecheras-awesomplete git://github.com/rbecheras/awesomplete.git
tombola-awesomplete git://github.com/tombolaltd/awesomplete.git
```

I installed the first and when I want to build the 'tags'-example from here ( http://leaverou.github.io/awesomplete/#advanced-examples ) it gives me this error:

```
Uncaught TypeError: this.input.setAttribute is not a function
```

Perhaps someone can help? What does this error mean? ( I only included the `awesomplete.js` and `awesomplete.css` , not the `index.js` ). (the other example, the first on the page, does work)

**Comment by haheute** [comment]
I had to change the example:

```
<script type="text/javascript">
    $(document).ready(function() {
        var input = document.getElementById("tags");
        new Awesomplete(input, {
        //.....
```

**Comment by 37** [comment]
Hey I'm having the same issue with the error:

"this.input.setAttribute is not a function"  - line 15 (awesomplete.js)

I changed the example as you listed and kept receiving the same error - any pointers?

**Comment by haheute** [comment]
the input has the same id as in the javascript?
`<input id="tags">` 
or
`var input = document.getElementById("your_id");`

**Comment by 37** [comment]
I think I worked it out, the new Awesomplete method cannot handle multiple objects in one instantiation - since I was using a class as the selector (also tried using input[data-multiple] as in the demo, though had multiple inputs with the same qualifier). Your usage of an ID in the call reference worked well, I think I need to do something along the lines of:

```
var Inputs = $('.your_classname');

for (i=0; i < Inputs.length; i++) {
    var input = Inputs[i];
    new Awesomplete(input, {
        filter: function(text, input) {
            return Awesomplete.FILTER_CONTAINS(text, input.match(/[^,]*$/)[0]);
        },

        replace: function(text) {
            var before = this.input.value.match(/^.+,\s*|/)[0];
            this.input.value = before + text + ", ";
        }
    });
}
```

P.s. Thanks!
