### ISSUE TITLE
Replace function could be more better

### ISSUE THREAD

**Issue by hamzadhamiya** [LeaVerou/awesomplete#16752]
If <code>replace</code> function's parameter returns the whole item instead of text then I could've used it in my live searching bar. Like when user hit enter, the page redirects to <code>href</code> link. But it doesn't return the item, item returns the text.

**Comment by fernandomoraes** [comment]
Hello , I am developing a search bar using a dsl . What did you specifically is developing ?

**Comment by vlazar** [comment]
Inside the `replace` method as in the other Awesomplete methods `this` references instance.

In any instance you have `this.ul` and `this.index`. So the selected `<li>` item would be:

``` javascript
this.ul.children[this.index]
```
