### ISSUE TITLE
open function not working when I use jquery on 

### ISSUE THREAD

**Issue by MahmoudFawzy** [LeaVerou/awesomplete#16754]
``` javascript
$('.test_control').each(function(i,elm) {
                var awesomplete = new Awesomplete(elm);
                $(elm).on('dblclick', function () {
                    awesomplete.open();
                }).on('awesomplete-selectcomplete', function (event) {
                    $(elm).trigger('change');
                    event.preventDefault();
                    event.stopPropagation();
                    return false;
                });
            });
```

**Comment by rsurjano** [comment]
i think that jquery is not required, awesomplete use pure javascript

**Comment by danielabar** [comment]
Can anyone provide a code example on how to use the events, for example `awesomplete-selectcomplete`?

**Comment by danielabar** [comment]
Think I answered my own question. Given that `inputElement` is a reference to the dom input element:

``` javascript
inputElement.addEventListener('awesomplete-selectcomplete', () =>  {
  let selectedValue = inputElement.value;
  // do something with selectedValue...
});
```

**Comment by vlazar** [comment]
Not related to jQuery.

Currently the `awesomplete.open()` just makes UL visible and selects first item if `autoFirst: true` option was used.

What LIs will appear in UL depends on what was typed into `<input>` element and what value was used in `minChars` option (default is `2`).

For any items to be shown in UL you also need to:
- set an `<input>` value and/or change `minChars` option
- call `awesomplete.evaluate()` which will add matched items as LIs to UL
