### ISSUE TITLE
clear (x) button to reset the input

### ISSUE THREAD

**Issue by gitaw** [LeaVerou/awesomplete#16750]
I started using awesomplete as a search box, in which case it is nice to have an xbutton to clear the search. Easy to rig-in but perhaps nice to include as an boolean JS property when calling the constructor?

**Comment by Cathbar2** [comment]
hello

You can do something like this without bool :

```
<button onclick="Clear()"> Clear button </button>

<script>
function Clear(){
 document.getElementById('ID of the search bar').value = "";
}
</script>
```

This is with bool:

```
 <script>
        var bool = true;
 </script>

<button onclick="Clear(bool)"> Clear button </button>

<script>
        function Test(boolean) {
            if (boolean == true) {
                document.getElementById('ok').value = "";
            }
        }
    </script>
```

**Comment by LeaVerou** [comment]
Just use `<input type="search" />` and it comes with that button already in many browsers. I don’t think this is something that fits in the scope of Awesomplete.

**Comment by gitaw** [comment]
Thanks, Lea!
