### ISSUE TITLE
Awesomplete is not defined

### ISSUE THREAD

**Issue by rm-rf-etc** [LeaVerou/awesomplete#16765]
![screenshot 2015-09-12 10 01 50](https://cloud.githubusercontent.com/assets/5067463/9832616/60ea8b18-5935-11e5-82f2-b79d4e14bbaa.png)

Pretty obvious why this is happening: `Awesomplete` is not defined anywhere in awesomplete.js. After reading the code, I don't notice any obvious candidates.

**Comment by esseb** [comment]
Fixed by https://github.com/LeaVerou/awesomplete/commit/42fbdff08c55b90086d7c98ac8fdd145040f6cfa it seems, but no release with this fix yet.

**Comment by vlazar** [comment]
@esseb What exactly do you mean by release?

**Comment by esseb** [comment]
@vlazar https://github.com/LeaVerou/awesomplete/releases

**Comment by vlazar** [comment]
Yeah, well, bower and npm packages also should be released someday :)

**Comment by mrkevinze** [comment]
I encountered the same error but I'm not sure if it's totally related to the discussion so far (I have just started using awesomplete). In their [example](https://leaverou.github.io/awesomplete/), they ask you to include 

<pre><code>script src="awesomplete.js" async</code></pre>

However, I was calling new Awesomplete(...) in another js file which I included in my html and it said that it was not defined. I later realized that removing the async tag solves it, as it ensures their js file is parsed first before mine.

**Comment by vlazar** [comment]
@kvnlte The original issue was a bug, which has been fixed. In this sense, the error you've encountered is not related to this issue. But in a sense, that in both cases `Awesomplete` can be undefined at the time of  `new Awesomplete(...)` call - yes, it is related.

The `async` was added in docs in fbba0fdb7d0c421226e31c7c90fd918704314760.

@LeaVerou Might be a good idea to mention this in docs somehow, or revert the commit above to avoid confusion. E.g. some people may not be aware of `async` attribute and it's effect at all.

**Comment by vlazar** [comment]
Fixed by 42fbdff08c55b90086d7c98ac8fdd145040f6cfa

**Comment by eyalev** [comment]
Still happening in my case..
