### ISSUE TITLE
String is not a function, error

### ISSUE THREAD

**Issue by rm-rf-etc** [LeaVerou/awesomplete#16764]
I assume this is the minifier's fault. Is it not following the ASI rules?

![screenshot 2015-09-12 06 14 20](https://cloud.githubusercontent.com/assets/5067463/9832592/8943bf90-5934-11e5-8698-84fdacba875d.png)

Suggested fix: change `(function(){` to `;(function(){`.

**Comment by blazarfox** [comment]
I believe someone suggested removing the double quotes around the comment at the top. The error seems to be in line with that as it almost seems to assume it is an unescaped string. (my best guess)

**Comment by blazarfox** [comment]
Here  is the suggestion : https://github.com/LeaVerou/awesomplete/issues/16770

**Comment by vlazar** [comment]
@rm-rf-etc You can close this issue, it's already being solved and merged in https://github.com/LeaVerou/awesomplete/commit/66837d556b2927ac5c156d890c13165291ab9b25#diff-7b5ed85343ecac61d1197e3f969efe51L1

**Comment by vlazar** [comment]
This issue was solved and make was replaced by gulp.
