### ISSUE TITLE
autocomplete off/false

### ISSUE THREAD

**Issue by kartheekgj** [LeaVerou/awesomplete#16766]
Hi,

I recently came across this issue while using the awesomplete plugin recently chrome still does autofill from history even if autocomplete="false" then i came across this question and answer( http://stackoverflow.com/a/30081850 ) so i think according to this you need to set an attribute while initialization as 'this.input.setAttribute("autocomplete", "off");' 

Also one more source of the issue is 
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by vlazar** [comment]
@kartheekgj This can be closed, since "false" was changed back to "off" in 66837d556b2927ac5c156d890c13165291ab9b25
