### ISSUE TITLE
return different variable

### ISSUE THREAD

**Issue by ghost** [LeaVerou/awesomplete#16762]
Hi Anna,

I'd like to have search for stock markets, which is a field "ticker: name" but to return only the ticker part in the box. In general "ID: description" with Regex search but return ID.
I guess an example is search box of finance.google.com.

BTW, your awesomplete is awesome.
Thank you
Khosro

**Comment by vlazar** [comment]
**To everyone interested in differentiating value from displayed text, aka key/value feature, aka array of objects feature.**

The code is ready and it's almost 100% backward compatible. To ensure everything working fine for you we need your help with testing it in the wild before it's released. See this PR: [Separate label/value for each suggestion in list](https://github.com/LeaVerou/awesomplete/pull/16852)

**Comment by vlazar** [comment]
Separate `label/value` is landed #16866
It is also possible to initialize list with separate `label/value` via `<datalist>` or `<ul>`.

Read about different `label` and `value` at the end of [Basic usage](http://leaverou.github.io/awesomplete/#basic-usage) section and about new `data` method at the end of [Extend](http://leaverou.github.io/awesomplete/#extensibility) section.
