### ISSUE TITLE
Triggering API call from click event

### ISSUE THREAD

**Issue by powerbuoy** [LeaVerou/awesomplete#16767]
I'm trying to trigger a .select() call when clicking a button next to the awesomplete input, but whatever function I call (I've tried open(), evaluate() and others too) absolutely nothing happens except that the awesomplete dropdown closes.

It seems as if the normal "click outside awesomplete to close it" code has higher priority or something?

If I change my click event to a mousedown event it starts working so this is how I've solved it at the moment, but just thought I'd point this out and perhaps get some clarification as to why this is happening.

Thanks

**Comment by vlazar** [comment]
@powerbuoy Yes, the item is selected on `mousedown` event. See a related discussion here https://github.com/LeaVerou/awesomplete/pull/16715#issuecomment-114005608

I'm closing this issue for now, until we have a super robust test suite with cross-browser testing setup. However...

@LeaVerou What's your opinion on this:

I think we should later consider using `click` as it makes more sense than `mousedown`. A standard behavior is for `click` to work after `mouseup` only if it happens on same element as a `mousedown` event.

For example you can press mouse button on item, then move mouse cursor outside completer, then un-press mouse button. This shouldn't be considered as item was really selected.

**Comment by LeaVerou** [comment]
Yes, we should. As I've mentioned elsewhere, I originally had click there and changed it to mousedown because Safari was a douchebag.
