### ISSUE TITLE
In Safari for Mac, the native autocomplete are show on top of awesomplete

### ISSUE THREAD

**Issue by fagionato** [LeaVerou/awesomplete#16778]
Hi there,

When using Safari, and starts typing in an input, the awesomplete is correctly displayed, but the safari native autocomplete are also displayed, and on top of the awesomplete, making it unusable.

I already tried to put autocomplete and spellcheck=false in the input, but didn't work.

Is there any workaround for it?

Thanks, Anderson.

**Comment by vlazar** [comment]
Might be related to #16766 which is fixed for some time now.

@fagionato Can you please check with latest version of awesomplete and check if you still have an issue?

If the issue still exists please reopen an also provide more info:
- OSX version
- Safari version
- example on Plunker/JSFiddle would be also useful unless this issue can be reproduced directly on the docs page over at http://leaverou.github.io/awesomplete/
