### ISSUE TITLE
Remove double quotes in awesomplete.min.js title

### ISSUE THREAD

**Issue by JonathanDcstr** [LeaVerou/awesomplete#16770]
Quote causes an error in the console.

<img width="793" alt="screen shot 2015-10-21 at 10 53 52" src="https://cloud.githubusercontent.com/assets/9802068/10632034/17462172-77e2-11e5-813e-6d925696af97.png">

**Comment by LeaVerou** [comment]
Huh, that's super odd. Pull request to remove the quotes?

**Comment by vlazar** [comment]
@JonathanDcstr You can close this issue, it's already being solved and merged in https://github.com/LeaVerou/awesomplete/commit/66837d556b2927ac5c156d890c13165291ab9b25#diff-7b5ed85343ecac61d1197e3f969efe51L1
