### ISSUE TITLE
Submit form when user click on a suggestion

### ISSUE THREAD

**Issue by Zebra447** [LeaVerou/awesomplete#16797]
How can i do this?

Thanks!

**Comment by TxHawks** [comment]
@anarchoi -
When an item is clicked, two events are fired - `awsesomplete-select` (on click before text in the input is replaced),  and `awesomplete-selectcomplete` (after the selection has been applied).

you can do: 

``` javascript
inpulElement.addEventListenr('awesomplete-selectcomplete', function(e){
  // Submit form
});
```

**Comment by Zebra447** [comment]
I tried it but it doesn't work, what did i do wrong ?

<form id=\"search_form\" method=\"GET\" action=\"$http://www.$domain/\">
<input type=\"search\" id=\"search\" name=\"search\" class=\"awesomplete\">
</form>

inpulElement.addEventListenr('awesomplete-selectcomplete', function(e){
  $(\"#search_form\").ajaxSubmit({url: '$http://www.$domain/', type: 'get'})
});

**Comment by ansballard** [comment]
There are a couple typos in the example code.

``` javascript
// $("#search").on("awesomplete-selectcomplete", function(event) { // jQuery version since you're already using ajax
document.getElementById("search").addEventListener("awesomplete-selectcomplete", function(event) {
  $("#search_form").ajaxSubmit({url: "$http://www.$domain/", type: "get"});
});
```

This is more of a general javascript question since there are several events fired that you can hook into. If you're still having trouble you may want to try [the MDN article on adding event listeners](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).

**Comment by LeaVerou** [comment]
Given that this seems to be a general JS question (and it has been answered, to the best of our knowledge about OP's code), I’m closing this.
