### ISSUE TITLE
Take value of selected option

### ISSUE THREAD

**Issue by cristo1985** [LeaVerou/awesomplete#16793]
Hi, if i include value on the option it's possible to take value from javascript of selected item from awesome autocomplete?

<option value="xxx">yyyy</option>

I wanna take xxx how can i?
Cris

**Comment by vlazar** [comment]
Selected suggestion item is available as `text` event property for `awesomplete-highlight`, `awesomplete-select` and `awesomplete-selectcomplete` events.

```javascript
Awesomplete.$.bind(input, {
  "awesomplete-selectcomplete": function(evt) {
    console.log(evt.text); // String {label: "Java", value: "Java", valueOf: function, toString: function}
  }
});
```
