### ISSUE TITLE
Selecting multiple items

### ISSUE THREAD

**Issue by rajitha-bandara** [LeaVerou/awesomplete#16799]
Thanks for this great plugin.
I want to initialize autocomplete using JavaScript and select multiple items.
According to docs, this can be done with data-multiple attribute. But I need this in JavaScript.

I'm using below code.

``` javascript
var awesomplete = new Awesomplete(input, {
            minChars: 2,
            maxItems: 5,
            filter: Awesomplete.FILTER_STARTSWITH,
            autoFirst: true
        });
```

Thanks,

**Comment by vlazar** [comment]
You don't need to use `data-multiple` at all. It's only use is to find HTML element with `$('input[data-multiple]')`.

 But you do need some additional JS for awesomplete to work with multiple values. See `filter` and `replace` functions in an example below.

From an example under **Multiple values** section:

``` html
<input data-list="CSS, JavaScript, HTML, SVG, ARIA, MathML" data-multiple />
```

``` javascript
new Awesomplete($('input[data-multiple]'), {
    filter: function(text, input) {
        return Awesomplete.FILTER_CONTAINS(text, input.match(/[^,]*$/)[0]);
    },

    replace: function(text) {
        var before = this.input.value.match(/^.+,\s*|/)[0];
        this.input.value = before + text + ", ";
    }
});
```

**Comment by vlazar** [comment]
JS in examples was hidden due to visual bug. See related #16801
