### ISSUE TITLE
Selecting an Autocomplete suggestion should keep the focus on the input box

### ISSUE THREAD

**Issue by lordspace** [LeaVerou/awesomplete#16808]
It would be nice to have Autocomplete to keep focus on the box after selecting the first item.

**Comment by LeaVerou** [comment]
The box? You mean the input? The input shouldn't lose focus, yes. If it does, I'd consider it a bug.

**Comment by lordspace** [comment]
Yep. It does loose focus.

**Comment by haroldiedema** [comment]
It loses focus when you click an element from the list. It stays focused when selecting an item with the keyboard.

**Comment by lordspace** [comment]
What if you click on the suggestion with the mouse?

**Comment by haroldiedema** [comment]
@lordspace That is what I meant, sorry.

It loses focus if you **click** on the suggestion with your **mouse**.
It stays in focus (or refocuses) if you **select** the suggestion with your **keyboard** (and pressing enter).

**Comment by lordspace** [comment]
cool

On Tue, Jan 5, 2016 at 1:07 AM, Harold Iedema notifications@github.com
wrote:

> @lordspace https://github.com/lordspace That is what I meant, sorry.
> 
> It loses focus if you _click_ on the suggestion with your _mouse_.
> It stays in focus (or refocuses) if you _select_ the suggestion with your
> _keyboard_ (and pressing enter).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeaVerou/awesomplete/issues/16808#issuecomment-168839977
> .

## 

Custom Web Development, Computer Training, WordPress Plugins, Facebook and
Mobile apps, Domains & Hosting
Phones: 647-478-6512 | US: 716-514-8880
Site: http://orbisius.com

**Comment by LeaVerou** [comment]
Confirmed.

**Comment by vlazar** [comment]
I'll take this one. Need to cover it by tests an find a good way to test focus/blur anyway.

**Comment by vlazar** [comment]
Fixed in #16813
