### ISSUE TITLE
Multiple values example highlights matched chars only the first time

### ISSUE THREAD

**Issue by vlazar** [LeaVerou/awesomplete#16814]
Reproduce:
1. Type `c` into field. See `c` matches highlighted.
   <img width="458" alt="multiple-values-1" src="https://cloud.githubusercontent.com/assets/7262/12216242/1b1ac76e-b6ec-11e5-9c59-6b70c55ae289.png">
2. Select `CSS` and press Enter.
3. Type `c` into field. See no matches highlighted.
   <img width="455" alt="multiple-values-2" src="https://cloud.githubusercontent.com/assets/7262/12216245/21a8b8e8-b6ec-11e5-8a48-7003bb460a4b.png">

This is one of 2 separate issues from #16749

**Comment by nodiscc** [comment]
Affects https://github.com/shaarli/Shaarli/issues/265 (sorry for the noise,  will help us keep track of this bug on our side)

**Comment by teqnology** [comment]
Here #16886 I've added the `item` code replacement that needs to be added to your "multi-valued" awesomplete function.

**Comment by ArthurHoaro** [comment]
This issue has apparently been fixed at some point.

![](http://i.imgur.com/xSrdoTh.png)
