### ISSUE TITLE
Page demos problems in Firefox 44

### ISSUE THREAD

**Issue by pocesar** [LeaVerou/awesomplete#16836]
When using the first input in the page https://leaverou.github.io/awesomplete/ it shows as this (double tooltip):

![fireshot capture 2 - awesomplete_ ultra lightweight high_ - https___leaverou github io_awesomplete_](https://cloud.githubusercontent.com/assets/461084/12701121/93e93f22-c7e5-11e5-8644-882eaebbf099.png)

then after selecting the first item:

![fireshot capture 3 - awesomplete_ ultra lightweight high_ - https___leaverou github io_awesomplete_](https://cloud.githubusercontent.com/assets/461084/12701124/9a2e4706-c7e5-11e5-9ee0-fda57de7609c.png)

and down with the combobox dropdown, the toggle is misaligned

![fireshot capture 1 - awesomplete_ ultra lightweight high_ - https___leaverou github io_awesomplete_](https://cloud.githubusercontent.com/assets/461084/12701128/bd3e7c34-c7e5-11e5-8805-460c56ed23f6.png)

**Comment by vlazar** [comment]
Awesomplete was included twice by mistake. This created 2 completer instances. Fixed in 6c20ebe

**Comment by vlazar** [comment]
Closing this one since the first bug is fixed and second one is in separate issue now #16838

**Comment by pocesar** [comment]
:+1:

**Comment by TxHawks** [comment]
This brings up an issue though.

Should Awesomplete check if an input is already initialized before
initializing?

Could be done by checking the Awesomplete.all array

**Comment by vlazar** [comment]
Yes.

**Comment by LeaVerou** [comment]
I’m not so sure. It introduces a performance overhead on **every** use for little benefit (since including it twice is essentially the author's bug).
I'm not necessarily saying no, I'm saying "yes" is not that obvious to me.

**Comment by vlazar** [comment]
Not necessarily performance overhead. Including script twice is an obvious error. Creating new instance for input, which already has awesomplete maybe not.

Anyways, won't implement if it adds significant performance overhead or complicates code to much.

**Comment by TxHawks** [comment]
I think the easiest way to do this is to check is `input` is the same as
one of the `input`s in _.all just before element creation.

I don't think the performance overhead should be significant, as everything
is already cached, so there is no unneeded DOM querying.

I think the check can probably be done pretty neatly with `_.all.reduce()`

**Comment by LeaVerou** [comment]
Why `reduce` and not `indexOf`?

**Comment by ghost** [comment]
Fuck you!  Stop emailing me

Thank you,
Stacey

**Comment by LeaVerou** [comment]
LOL, Stacey, nobody is emailing you. You (or someone using your email) has subscribed to this conversation. Just press unsubscribe.

**Comment by ghost** [comment]
I would have 3,823 emails ago.  There is no unsubscribe.  And thank you for not taking my message personally.  Apple should allow blocking of email rather than just junk

Thank you,
Stacey

**Comment by LeaVerou** [comment]
The notifications you are getting are automated for every message posted on this conversation. It's not an email conversation, the emails are just notifications that you can reply to. The actual conversation is on the website. Note the "View it on Github" link under every message? That takes you to the website.
However, to unsubscribe, I imagine you need to log in, so if you didn't register, you need to figure out who did using your email.

**Comment by ClausMandal** [comment]
Lea you radiate professionalism left and right! Well done.

**Comment by TxHawks** [comment]
You could either use `reduce` or `all.map().indexOf()`.

You can't use `indexOf()` directly, because `Awesomplete.all` is an array of objects, each with a property of `input`, which is the HTML element

**Comment by LeaVerou** [comment]
Yes, that's what I meant. I think it would be more readable than reduce.

**Comment by TxHawks** [comment]
Sure thing. Want me to submit a PR?

**Comment by LeaVerou** [comment]
Eh, why not. :)

**Comment by vlazar** [comment]
The short answer would be - tests. I need to figure out a clean way to test Awesomplete's addition via script tag to the page. This is pretty much the only part not covered by tests yet.
