### ISSUE TITLE
In Combobox dropdown example the toggle is misaligned

### ISSUE THREAD

**Issue by vlazar** [LeaVerou/awesomplete#16838]
@pocesar I've created this separate issue for second part of your #16836

In Firefox:
![fireshot capture 1 - awesomplete_ ultra lightweight high_ - https___leaverou github io_awesomplete_](https://cloud.githubusercontent.com/assets/461084/12701128/bd3e7c34-c7e5-11e5-8805-460c56ed23f6.png)

@smargh Can you look at it please, since you are the author of this example?

**Comment by fractaledmind** [comment]
I'll look into it and find a fix.

**Comment by fractaledmind** [comment]
PR  #16839 fixes this.
