### ISSUE TITLE
Click event on selected item from list

### ISSUE THREAD

**Issue by cristo1985** [LeaVerou/awesomplete#16848]
Hi,
is there a trick when i click on selected item from list and call a function?
Thanks
Cris

**Comment by TxHawks** [comment]
Selecting an item fires two events you can listen to -
`awesomplete-select`, which is fired after you click, but before the
selection is submitted, and `awesomplete-selectcomplete` which is fired
after the selection has been submitted. You can use listen to them and run
a function when they are called.

**Comment by cristo1985** [comment]
Ok. Is there an example? For this?

**Comment by bherrero** [comment]
Hi,
I'd be interested in an example for listening the event too, if posible.
Thanks

**Comment by TxHawks** [comment]
```js
const input = documenet.getElementById('my-input');

new Awesomplete(input);
input.addEventListener(`awesomplete-select`, (e) => {
  // This callback will be called whenever a selection is made.
  console.info('A selection was made');
});
```

**Comment by bherrero** [comment]
Thank you @TxHawks
