### ISSUE TITLE
Happy birthday, Awesomplete!

### ISSUE THREAD

**Issue by vlazar** [LeaVerou/awesomplete#16859]
:date: Feb 19
Awesomplete is now 1 year old! :gift:

So far we have:
- 35 contributors
- 233 commits since the very first one
- 50 changed files with 3,602 additions

**Comment by LeaVerou** [comment]
Woohoo! Happy birthday Awesomplete! :)

**Comment by LeaVerou** [comment]
LOL, I love that you added the LGTM label to this :P

**Comment by vlazar** [comment]
BTW, [Awesomplete looks like a beautiful butterfly](http://codeology.braintreepayments.com/leaverou/awesomplete)!
