### ISSUE TITLE
Option to ignore accents

### ISSUE THREAD

**Issue by willbelr** [LeaVerou/awesomplete#16858]
Thanks a lot for your work, it is really simple to implement and fits perfectly in my website. The only downside is that I need it to ignore accents when matching the input with the database.

As an exemple, if I type "iles", "îles" should popup.
if I type "Cèdres", "Cedres" should popup, and so on..

Hopefully it should not be too hard to implement, I guess.
Thanks in advance and keep on your great work!

**Comment by LeaVerou** [comment]
This should be pretty easy to do with a custom `filter` function.

**Comment by willbelr** [comment]
**I did this:**

`
function homostr(ville) {
    ville = ville.toLowerCase();
    ville = ville.replace(/(.*?)/, "");
    ville = ville.replace(/[éèêë]/g,'e');
    ville = ville.replace(/[ôòö]/g,'o');
    ville = ville.replace(/[îïì]/g,'i');
    ville = ville.replace(/[ûüù]/g,'u');
    ville = ville.replace(/[âäà]/g,'a');
    ville = ville.replace(/[ÿ]/g,'y');
    ville = ville.replace(/[-'\s]/g,'');
    ville = ville.replace('ste','st');
    ville = ville.replace('sainte','st');
    ville = ville.replace('saint','st');
    return(ville);
}

_.FILTER_VILLES = function (text, input) {
    text = homostr(text);
    input = homostr(input);
    return RegExp($.regExpEscape(input.trim()), "i").test(text);
};
`

**Now if I write "iles" it matches "Îles" but the result does not get the <mark> tag,
So I tried to do something similar with the _ITEM function:**

`
_.ITEM = function (text, input) {
    txt = homostr(text);
    ipt = homostr(input);
    var html = ipt === '' ? txt : text.replace(RegExp($.regExpEscape(input.trim()), "gi"), "<b>$&</b>");
    return $.create("li", {
        innerHTML: html,
        "aria-selected": "false"
    });
};
`

But I could not get it to work

**Comment by vlazar** [comment]
Your item function doesn't work, because you are doing match on original strings `text` and `input`, which are not converted by `homostr`. This change will do the trick:

``` diff
- text.replace(RegExp($.regExpEscape(input.trim()), "gi"), "<b>$&</b>");
+ txt.replace(RegExp($.regExpEscape(ipt.trim()), "gi"), "<b>$&</b>");
```

But then, of course, you want to show original string in completer, so you also have to undo the changes made by `homostr` (e.g. "Cè" was changed to "ce"):

``` javascript
var originalMatch = text.substr(html.indexOf("<b>"), ipt.trim().length);
html = html.replace(RegExp($.regExpEscape(ipt.trim()), "gi"), originalMatch);
```

So the whole item function can be:

``` javascript
function (text, input) {
    var txt = homostr(text);
    var ipt = homostr(input.trim());

    // match homostr processed strings first
    var html = ipt === '' ? txt : txt.replace(RegExp($.regExpEscape(ipt), "gi"), "<b>$&</b>");
    // and then undo homostr changes e.g. change "ce" back to "Cè"
    html = html.replace(RegExp($.regExpEscape(ipt), "gi"), text.substr(html.indexOf("<b>"), ipt.length));

    return $.create("li", { innerHTML: html, "aria-selected": "false" });
}
```

**Comment by willbelr** [comment]
Thank you vlazar for pointing out the right path. Your code worked well, but only to replace the input. So I adapted it to replace the beginning and end of string. I realized there was a conflict with between two of my scripts; I use homostr() for form validation, so city names like ste-perpètue would match Sainte-Perpétue, for exemple. The problem was that it also change the length of the string, so I ended up making a parallel version of homostr, just to remove accents.

``` javascript
function removeAccent(str) {
    str = str.toLowerCase();
    str = str.replace(/[éèêë]/g,'e');
    str = str.replace(/[ôòö]/g,'o');
    str = str.replace(/[îïì]/g,'i');
    str = str.replace(/[ûüù]/g,'u');
    str = str.replace(/[âäà]/g,'a');
    str = str.replace(/[ÿ]/g,'y');
    return(str);
}

_.FILTER_VILLES = function (text, input) {
    text = removeAccent(text);
    input = removeAccent(input);
    return RegExp($.regExpEscape(input.trim()), "i").test(text);
};

_.ITEM = function (text, input) {
    var txt = removeAccent(text);
    var ipt = removeAccent(input.trim());
    var html = ipt === '' ? txt : txt.replace(RegExp($.regExpEscape(ipt), "gi"), "<b>$&</b>");
    html = html.replace(RegExp($.regExpEscape(ipt), "gi"), text.substr(html.indexOf("<b>"), input.length)); //replace the input
    html = html.replace( html.substr(html.indexOf("</b>") + 4) , text.substr(html.indexOf("</b>") - 3) ); //replace end of str
    html = html.replace( html.substr(0, html.indexOf("<b>")) , text.substr(0, html.indexOf("<b>")) ); //replace beginning of str
    return $.create("li", { innerHTML: html, "aria-selected": "false" });
}
```

It is not a perfect solution, but good enough for a compromise.
Thank you!

Edit: I found a way to get around the second problem. In the database, I kept all the city name intact, with Saint-... Then on the field I added an onKeyUp event that trigger this function:

``` javascript
function formatSt(field) {
    var field = document.getElementById(field);
    if (field.value.length < 5) {
        var replace = false;
        fvalue = field.value.toLowerCase();
        if (fvalue == 'st-') { field.value = 'Saint-'; replace = true; }
        if (fvalue == 'ste-') { field.value = 'Sainte-'; replace = true; }
        if (replace == true) {
            var awesome = new Awesomplete(field);
            awesome.evaluate();
            field.focus();
        }
    }
}
```

Hope this helps!
