### ISSUE TITLE
Is it possible to add validation?

### ISSUE THREAD

**Issue by its-me-julien** [LeaVerou/awesomplete#16856]
Hello,

I'm not sure if I'm asking this in the right section, if not i'm sorry and please delete my post.

I've added the script on my website and it's working well. I'm trying to add data validation so that only values in the list can be selected, any other input will return an empty value.

Here's my current code:

```
<script>
    var ajax
        ajax = new XMLHttpRequest()
        ajax.open("GET", "http://tribesports.com/pages/parkrun-event-list", true)
        ajax.onload = function() {
            {
                    var list = JSON.parse(ajax.responseText).map(function(i) {return i.tshirtname;})

                    new Awesomplete(document.querySelector("#parkrun-name-wrapper input"),{list:list});
        }



    }
        ajax.send();
  </script>
```

and here's an example of what I'm trying to achieve: http://jsfiddle.net/Ra96R/2/ (in the example autocomplete jquery ui is being used)

Is it something that awesomplete can do? How could I achieve this?

Thank you,

**Comment by vlazar** [comment]
I'm not quite sure what exactly are you trying to achieve, but you can prevent selecting an item based on some criteria with `awesomplete-select` event:

``` javascript
Awesomplete.$.bind(input, { "awesomplete-select": function(evt) {
    // prevent selection based on selected item value here:
    if (evt.text == "foo") {
        evt.preventDefault();
    }
});
```

See http://jsfiddle.net/Ra96R/23/

**Comment by its-me-julien** [comment]
Thanks for your reply vlazar, sorry if my question was confusing.

We have an online shop and use awesomplete to customize t-shirts with different names of events. Awesomplete is currently working fine, if a customers enters an event name, he's likely to find it in the list and select the right event. However we're facing an important issue : a customer can enter whatever value he wants (that is not in the list) and click on the buy button. Therefore I'm trying to get the script to validate the value in the box, if the value is not in the list and the customers clicks on something else than the autocomplete box, the box value should return to blank. The fiddle http://jsfiddle.net/Ra96R/2/ is similar to what I'm trying to achieve, if you try to enter just the letter A without selecting a value, the box will return to blank when you click on something else.

Ideally we would even have an alert coming up, saying they need to find and select the value in the dropdown list.

Thank you,

**Comment by LeaVerou** [comment]
@vlazar, what he's trying to do is not allow inputs that are not in the list.
@JulienT This is definitely possible and should be pretty easy, but I don't have time to look into it right now.

Just wanted to note that once we figure this out, we should polish the code and add it to the advanced examples, as I'm pretty sure it's a common use case. Basically, getting Awesomplete to function like a searchable `<select>`. E.g. instead of making someone pick their country from a huge list, let them type the first characters and pick it from the suggestions, but not allow custom countries.

**Comment by vlazar** [comment]
If validation  on blur is what you want, then this will work for you:

``` javascript
var availableTags = ["aaaa", "abbaba", "abababa", "bababa"];
var input = Awesomplete.$("#stdcodes");

new Awesomplete(input, { list: availableTags });

Awesomplete.$.bind(input, { "blur": function(evt) {
    if (availableTags.indexOf(input.value) == -1)
        input.value = "";
}});
```

See it live at http://jsfiddle.net/Ra96R/24/ (it wasn't saved first time, so it didn't worked)

**Comment by its-me-julien** [comment]
Awesome that's exactly what I was looking for - and it's working!
Thank you!

**Comment by vlazar** [comment]
> Basically, getting Awesomplete to function like a searchable <select>.

There is a separate request for this and it will require changes in Awesomplete to be supported by default.

**Comment by TxHawks** [comment]
@JulienT - 
I'd probably add validation when `enter` is pressed in addition to validating on `blur`.

Something along the lines of:

``` js
var availableTags = ["aaaa", "abbaba", "abababa", "bababa"];
var input = Awesomplete.$("#stdcodes");

new Awesomplete(input, { list: availableTags });

Awesomplete.$.bind(input, {
  "blur": function(evt) {
    if (availableTags.indexOf(input.value) == -1)
        input.value = "";
  },
  "keydown": function(evt) {
    var keyIsEnter = evt.keyCode === 13;
    if (keyIsEnter && availableTags.indexOf(input.value) == -1) {
      evt.preventDefault();
      input.value = "";
    }
  }
});
```

This will prevent the form from being submitted when `enter` is pressed, if it contains an invalid value.

**Comment by its-me-julien** [comment]
Thank you TxHawks for the improved code! Very useful!
