### ISSUE TITLE
Awsomecomlete doesnt work on IE

### ISSUE THREAD

**Issue by Dahlia-01** [LeaVerou/awesomplete#16861]
Thanks so much for an amazing easy search box. It doesnt seem to work on Internet Explorer.

**Comment by LeaVerou** [comment]
Version?

**Comment by Dahlia-01** [comment]
IE version 10

**Comment by LeaVerou** [comment]
Also, what do you mean “doesn’t work”? Is there a JS error? What happens?

**Comment by Dahlia-01** [comment]
Sorry, just found and fixed the bug. thanks
