### ISSUE TITLE
Custom event should be singular

### ISSUE THREAD

**Issue by anselmbradford** [LeaVerou/awesomplete#16876]
It looks like the custom `HTMLEvents` [here](https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L383) should singular `HTMLEvent`, right? It's only one event, and all native events are singular.

**Comment by vlazar** [comment]
It is a correct event type and it's one for **HTML event module**. See https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent

**Comment by anselmbradford** [comment]
Ahh, thanks @vlazar that's surprising.

**Comment by anselmbradford** [comment]
> The reason some events can be created using any of two event type strings is that DOM Level 3 Events changed the event type strings to be singular, while still supporting older plural names for backwards-compatibility.

Ah, got it. Legacy.
