### ISSUE TITLE
Why there is no semver or release tags?

### ISSUE THREAD

**Issue by emmenko** [LeaVerou/awesomplete#16873]
Hey guys,

I've been using this library for a while and it works pretty well.

Unfortunately the lack of versioning / releases is really a **problem**. 
The workaround of using the tip of the repository as a dependency is obviously very fragile. A simple breaking change can go easily unnoticed into production build because of the absence of a version.
Of course we could simply lock the dependency to a specific commit, but it's going to be hard then to "upgrade" as there is no related changelog to look at.

So my question is: why there is no versioning / release tags? I can live with the library not being published to `npm`, `bower`, etc, but having versions and keeping track of them should be a must IMHO.

Thanks

**Comment by vlazar** [comment]
There should be a 1.1 release soon. See https://github.com/LeaVerou/awesomplete/milestones/v1.1

**Comment by emmenko** [comment]
Ok, so is it planned to start using semver?

Thanks for the quick reply.

**Comment by vlazar** [comment]
@LeaVerou Speaking of server, should it be a 2.0 instead? There is a small known breaking change with suggestion item text API.

**Comment by emmenko** [comment]
> There is a small known breaking change with suggestion item text API.

That's the problem I discovered today :)

**Comment by vlazar** [comment]
> That's the problem I discovered today :)

Can you please share, maybe it's something we don't know about yet?

**Comment by emmenko** [comment]
Well, it's related to the change in #16866. 

The `replace` function used to return a `string` but now it returns a `Suggestion` which is an object with `{ label, value }`.

Wasn't that the "breaking change" you were talking about?

**Comment by vlazar** [comment]
Yes, did you had a problem with this or something else:

> One known issue is that accessing suggestion's characters by index won't work with old API. It's easy to fix though. Instead of item[idx] use item.value[idx] or item.label[idx] directly.

**Comment by LeaVerou** [comment]
> The replace function used to return a string but now it returns a Suggestion which is an object with { label, value }.

Did this break any of your old code? Its `toString` function makes it coerce into the old string when needed, but of course, it's still not bulletproof.

**Comment by vlazar** [comment]
The new version is 1.1 https://github.com/LeaVerou/awesomplete/issues/16850#issuecomment-197464182
