### ISSUE TITLE
Unpublished from NPM?

### ISSUE THREAD

**Issue by mauris** [LeaVerou/awesomplete#16871]
I get a 404 on npm. Did the package get unpublished?

**Comment by vlazar** [comment]
Related to #16850

**Comment by mauris** [comment]
@vlazar thanks for responding so quickly. appreciate and will wait patiently for the new updates

**Comment by vlazar** [comment]
Thanks for spotting this. I'm preparing for release right now, but @LeaVerou will publish it.

Please track progress here https://github.com/LeaVerou/awesomplete/milestones/v1.1

**Comment by vlazar** [comment]
@LeaVerou Can we address this quickly? https://github.com/LeaVerou/awesomplete/pull/16872

After that I just need to add a minified version, bump version and update changelog. Unless I'm missing something.

**Comment by vlazar** [comment]
Version 1.1 published
