### ISSUE TITLE
Highlighting not displayed on extra values when using "Multiple values"

### ISSUE THREAD

**Issue by tdruez** [LeaVerou/awesomplete#16886]
Hi Lea,

I've noticed an issue using the "Multiple values" example.
The highlighting on the suggestions works fine on the first item, but no anymore on the second item, thrid, and so on...
Reproducible using the input at http://leaverou.github.io/awesomplete/#multiple-values

Do you think this is something we can solve directly when creating the Awesomplete instance, or does this required a change in the library?

Thanks for Awesomplete by the way, it's an excellent piece of software :)

**Comment by vlazar** [comment]
Related #16814 (examples enhancement)

**Comment by vlazar** [comment]
Absolutely doable.

You need to define a custom `item` function, which is called to render each item. Original `item` function performs match on full input value. In Multiple values example you need to match against the last word in comma-separated list.

**Comment by teqnology** [comment]
Adding here the fix for this issue.
When adding your own `new Awesomplete('input[data-multiple]' ...`
just add the `item` function along with the `filter` and `replace`:

```
filter: function (text, input) {
    ...
}
item: function (text, input) {
    var s = input.split(",");
    var lastItem = s[s.length-1];
    var html = lastItem.trim() === '' ? text : text.replace(RegExp(Awesomplete.$.regExpEscape(lastItem.trim()), "gi"), "<mark>$&</mark>");
    return Awesomplete.$.create("li", {
        innerHTML: html,
        "aria-selected": "false"
    });
},
replace: function (text) {
    ...
}
```

**Comment by tdruez** [comment]
Fixed using the `item` function from https://leaverou.github.io/awesomplete/#multiple-values
