### ISSUE TITLE
Multiple value example doesn't highlight 2nd and subsequent values

### ISSUE THREAD

**Issue by payne92** [LeaVerou/awesomplete#16884]
The "multiple values" example on the main example/documentation page (here:  [https://leaverou.github.io/awesomplete/](https://leaverou.github.io/awesomplete/)) doesn't properly highlight 2nd and subsequent selected examples (in the drop down menu).

**Comment by vlazar** [comment]
Closing as duplicate of #16814

**Comment by payne92** [comment]
Sorry for duplicating an issue.

It's still an open problem, though, and all related problems have been marked as "closed".  

Is there an open issue tracking this problem?

Thanks!

**Comment by vlazar** [comment]
Yes, it's #16814 and it's open :)
