### ISSUE TITLE
Allow searching for string matches only from the start of elements

### ISSUE THREAD

**Issue by alexjurkiewicz** [LeaVerou/awesomplete#16885]
I'm implementing a username search, and I'd like awesomplete to only suggest matches based on the start of candidates. Eg searching for 'al' should show 'alexjurkiewicz' but not 'mallory'.

Is this possible?

**Comment by vlazar** [comment]
Yes, check out `filter` property docs here http://leaverou.github.io/awesomplete/#extensibility

By default `filter` is set to `Awesomplete.FILTER_CONTAINS` but you can use `Awesomplete.FILTER_STARTSWITH` or provide your custom function depending on your requirements.

**Comment by LeaVerou** [comment]
Thanks @vlazar, closing this now. :)

**Comment by alexjurkiewicz** [comment]
Thanks both! :)
