### ISSUE TITLE
Update options dinamicaly

### ISSUE THREAD

**Issue by rafaelcamargo** [LeaVerou/awesomplete#16891]
Is it possible? I would like to update my awesomeplete options after some events happen on my application. I read awesomplete docs, but still can't find any solution.

**Comment by rafaelcamargo** [comment]
Just realized how to do this after investigate instance object. I have just overwritten `_list` attribute with the new options and everything worked well.

**Comment by vlazar** [comment]
You can use `awesomplete.list` setter, the `_list` is private. See https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L110

**Comment by rafaelcamargo** [comment]
well, I am instantiating awesomplete this way: `var autocomplete = new Awesomplete(...)`

and all I see as instance methods/attributes is:
<img width="429" alt="screen shot 2016-05-18 at 10 48 32" src="https://cloud.githubusercontent.com/assets/4738687/15361075/785b65a4-1ce6-11e6-8ae9-9e6a278b92c2.png">

Am I doing something wrong?

**Comment by vlazar** [comment]
You can use `awesomplete.list = [ ... ]` to assign new list. You can't however use `awesomplete.list` to read current list, as there is no `list` getter, only a setter.

If you expand the `__proto__` property in developer tools you'll see prototype's properties. You need a `set list: function list(list)` property.

**Comment by El4a** [comment]
I'm having a similar issue; I can't get the setter to work. Only awesomeplete.list = [...] I can get working. The problem I have is, say the original data is ["stra"] . (theoretical weird data)
The data I want to replace it with (on the fly) is: ["straw", "strawberry"] (the original data is gone at this point).

Scenario: 
1) I type "stra" -> the correct match pops up
2) An action happens somewhere on the page that changes the data to the new dataset

What I would like to happen is:
The typeahead matches automagically change to display the options "straw" and "strawberry"

What happens:
the typeahead does not update untill it detects an inputchange. only after a keystroke, it will update to match the new data

Is there a way to achieve what I want? If this is not clear I'll make a fiddle
