### ISSUE TITLE
How to sort alphabetically

### ISSUE THREAD

**Issue by OscarWilde** [LeaVerou/awesomplete#16895]
Hi,

I can'f figure out how to sort the list alphabetically. Can you give my a hint?

Thanks in advance! Frank

**Comment by OscarWilde** [comment]
Ok, found it! 

Option is: sort: Awesomplete.SORT_BYORDER

**Comment by El4a** [comment]
Uhm, am I missing something? Where in the awesomplete.js file is there a SORT_BYORDER function? Can't find it.

**Comment by davidkna** [comment]
@El4a It doesn't need to be defined. `Awesomplete.SORT_BYORDER` is not defined and thus because no custom compare function is given to `Array.prototype.sort` it falls back to the default of sorting by order.
