### ISSUE TITLE
replace completion list?

### ISSUE THREAD

**Issue by russellyoung** [LeaVerou/awesomplete#16892]
Hi, here is something someone else has asked for which I'd like to get too (#16802). I want to replace my completion list with a new one fetched through ajax. It is working now through a pretty ugly hack - I remove the parent div of class "awesomplete" which you added and splice my original text element back in its place, and then load the words the same as the first time. This works, but I cringe at doing it. Is there a better way to do this?

Thanks so much for making this script available, it is not only useful and relatively easy to use, but as a relative js newbie looking over the code is helpful,

russell

**Comment by davidkna** [comment]
I think this should work:

``` javascript
var a = new Awesomplete(myInput, myOptions);
myInput.addEventListener('input', function() {
    var list = getNewListWithAjax();
    a.list = list;
    a.evaluate();
});
```

**Comment by russellyoung** [comment]
Thanks, that is much better.
