### ISSUE TITLE
How to deal with multiple instances?

### ISSUE THREAD

**Issue by francoism90** [LeaVerou/awesomplete#16908]
```
// Blade:
{!! Form::text('title', old('title'), ['class' => 'form-control', 'id' => 'title', 'autocomplete' => 'off', 'aria-autocomplete' => 'list', 'placeholder' => 'Enter title']) !!}
{!! Form::text('tags', old('tags'), ['class' => 'form-control', 'id' => 'tags', 'autocomplete' => 'off', 'aria-autocomplete' => 'list', 'placeholder' => 'Enter tags']) !!}

<script>
$.ajax({
  method: "GET",
  url: "{!! route('api.overview') !!}",
  dataType: "json"
})
.done(function(data) {
    new Awesomplete("#title",{ list: data.title });
    new Awesomplete("#tags",{ list: data.tags });
});
</script>
```

Is this the best solution? Or is it possible to add multiple instance in when calling Awesomplete?

Thanks!

**Comment by vlazar** [comment]
If you mean adding autocomplete to multiple inputs with one `new Awesomplete` call, then the answer is no. The first argument should be a single input element.

If you need the same options for all instances you can do it the same way as Awesomplete does for all `input.awesomplete` elements on DOM ready here https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L411-L413

Use:

``` javascript
Awesomplete.$$("input.awesomplete").forEach(function (input) {
    new Awesomplete(input, { list: someList });
});
```

**Comment by francoism90** [comment]
Many thanks, going to test! :)
