### ISSUE TITLE
Space character matches all items when minChars: 1 

### ISSUE THREAD

**Issue by nico-amsterdam** [LeaVerou/awesomplete#16934]
I have this HTML run in the browser (Firefox 48.0):
`<input class="awesomplete"                                                                                                       
       data-minchars="1"                                                                                                              
       data-maxitems="5"                                                                                                              
       data-list="China, India, Japan, Russia, UK, Wallis and Futuna" />`

when I enter a space character in the input field, 5 items are shown with 'highlighted' yellow stripes between all characters. But I was looking for 'Wallis and Futuna', which contains a space.

Also, when I search for 's '  (s with space), I get 'Wallis and Futuna' but also Russia.

Maybe I shouldn't expect that searches with special characters like the space work,
but the yellow striped results shown when just a space character is entered look really weird and that is certainly a bug.
![spaceselect](https://cloud.githubusercontent.com/assets/16443840/17771180/1b70db86-6542-11e6-9b34-5bf5f44203ea.png)

**Comment by LeaVerou** [comment]
Yeah, it's a bug. Probably due to trimming the input, so you end up with a zero-width regex that matches any character boundary :/

**Comment by vlazar** [comment]
@davidkna Care to do a PR with tests?

**Comment by vlazar** [comment]
@davidkna Thanks!
Fixed by #16977
