### ISSUE TITLE
Less opinionated CSS file

### ISSUE THREAD

**Issue by rikschennink** [LeaVerou/awesomplete#16931]
While Awesomeplete looks great, I always find myself overriding or stripping multiple styles when implementing it. It would be nice if the package would include a CSS file that was a little less opinionated.

So minimal positioning and handling of [hidden]/:empty state?

**Comment by LeaVerou** [comment]
Sadly, this is the common problem of styling widgets to which the Web platform has no good answer yet: Some people want a lean CSS file that they plan to style themselves, others want decent styles out of the box so they don't need to style anything. If you have any idea on how we could address both use cases, it would be very welcome. Splitting the styles in two CSS files is not an option, as I don't want to tell people to include two by default.

**Comment by rikschennink** [comment]
Yeah, it's a though cookie to crack, I've been struggling with this as well. Some ideas:
1. Add an **awesomplete.base.css** but still have the themed version as well, no need to embed both.
2. Move position related styles to JavaScript and only do theming in the CSS variant. Might feel wrong but the two are quite close relatives already.

**Comment by LeaVerou** [comment]
The first one could be workable, @vlazar what do you think? Do you have time to split them and set up a gulp task to concat?

**Comment by rikschennink** [comment]
Just wanted to thank you your quick response @LeaVerou I'll wait patiently for a possible solution.

**Comment by LeaVerou** [comment]
Since @vlazar is very busy with other work lately, do you want to give it a shot and send a PR? If you've worked with gulp before it should be very quick and if not, it's a chance to learn gulp :)

**Comment by LeaVerou** [comment]
Oops, closing was by accident!

**Comment by rikschennink** [comment]
I'll give it a go. Worked with Gulp before so should be fine.

**Comment by rikschennink** [comment]
Pull Request: https://github.com/LeaVerou/awesomplete/pull/16940

**Comment by vlazar** [comment]
Closing since #16940 is already merged in.
