### ISSUE TITLE
Compatibility issue with bootstrap?

### ISSUE THREAD

**Issue by shibathethinker** [LeaVerou/awesomplete#16935]
Thanks for the awesome library.
However I ran into a glitch which seems be a compatibility issue with Bootstrap.

I tried to test this with bootstrap on (see the form-control class)
       <input id="teacher_textbox" class="awesomplete form-control" aria-autocomplete="list" autocomplete="off" data-list="Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails" />

After this the look and feel of the auto complete list gets quite messed up.

**Comment by shibathethinker** [comment]
Thanks to #rwilson. I can close this issue.

**Comment by LeaVerou** [comment]
What was it?

**Comment by shibathethinker** [comment]
Please check this
https://github.com/LeaVerou/awesomplete/issues/13387

Needed to implement this suggestion to have this library work properly with bootstrap.
Actually, when I was initially combining this in a bootstrapped page, the suggestion items' style was getting lost.
