### ISSUE TITLE
Use data from a model instead of a list?

### ISSUE THREAD

**Issue by marine-b** [LeaVerou/awesomplete#16980]
I'm using awesomplete in rails 5 and I'm wondering if there's a way to use the data from a model instead of typing a list myself?

**Comment by vlazar** [comment]
It does no matter what server side technology you are using to generate HTML or serve JS. All you have to do is to provide a list of suggestions for Awesomplete.

For example, if you are using `data-list` attribute to initialize a list of suggestions just make sure Rails generates list separated with commas:

``` html
<input class="awesomplete"
       data-list="Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails" />
```

Or generate a separate HTML element for a list using Rails:

``` html
<input class="awesomplete" list="mylist" />
<datalist id="mylist">
    <option>Ada</option>
    <option>Java</option>
    <option>JavaScript</option>
    <option>Brainfuck</option>
    <option>LOLCODE</option>
    <option>Node.js</option>
    <option>Ruby on Rails</option>
</datalist>
```

Use any suitable way of initialization described in the docs http://leaverou.github.io/awesomplete/

**Comment by marine-b** [comment]
Thank you for your answer but what I need is to get the list from my database and I don't know how to do that.

**Comment by vlazar** [comment]
Please use Rails related documentation for such questions. Awesomplete has nothing to do with Rails.

Assuming you have `@model` instance and `@model.languages` is an array of strings like `[ "Ada", "Java", "JavaScript", "Brainfuck", "LOLCODE", "Node.js", "Ruby on Rails" ]` you can use:

``` ruby
<%= tag("input", class: "awesomplete", data: { list: @model.languages.join(", ") }) =>
```

To get:

``` html
<input class="awesomplete"
       data-list="Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails" />
```
