### ISSUE TITLE
There is a way to put everything in the same code?

### ISSUE THREAD

**Issue by Pabloduarte124** [LeaVerou/awesomplete#16987]
There is a way to put everything in the same code?

I try but does not work

**Comment by LeaVerou** [comment]
I have no idea what you're asking. Please elaborate?

**Comment by Pabloduarte124** [comment]
Accomplish this, but as I add a link to a datalist element? for example to Ada

https://dl.dropboxusercontent.com/s/vwytv0j1m7obrbe/example.txt

And how change the design?
