### ISSUE TITLE
event without jquery

### ISSUE THREAD

**Issue by lbottoni** [LeaVerou/awesomplete#16983]
can you show a simple example , how to do "awesomplete-select" event without jquery?

**Comment by lbottoni** [comment]
var obj=new Awesomplete('input[data-multiple]', {
    filter: function(text, input) {
        return Awesomplete.FILTER_CONTAINS(text, input.match(/[^,]*$/)[0]);
    },

```
replace: function(text) {
    var before = this.input.value.match(/^.+,\s*|/)[0];
    this.input.value = before + text + ", ";
}
```

});
document.getElementById("pippo").addEventListener("awesomplete-select", function(e){
  // User made a selection from dropdown. 
  // This is fired before the selection is applied
  alert(1);
}, false);

**Comment by vlazar** [comment]
You can also use Awesomplete's helper to attach event handlers:

``` javascript
// input is DOM element here
Awesomplete.$.bind(input, { "awesomplete-select": function (evt) { });
```
