### ISSUE TITLE
Is there way to get initialized awesomplete object by HTMLElement?

### ISSUE THREAD

**Issue by alies-dev** [LeaVerou/awesomplete#17033]
Is there way to get initialized awesomplete object by HTMLElement?
Something like this:
```js
const awesompleteInstance = Awersomplete.instance(document.getElementById('someId'));
```

The goal: change list using something like this: `awesompleteInstance.list = [1,2,3,4]`

**Comment by CaitlinWeb** [comment]
+1

**Comment by LeaVerou** [comment]
You can call `new Awesomplete(element, options)` manually. Check out the Basic Usage section and scroll a bit: http://leaverou.github.io/awesomplete/#basic-usage

**Comment by onecreative** [comment]
This doesn't appear to answer his question. The idea is to get an existing instance, not create a new one.

**Comment by hwdegroot** [comment]
@onecreative I am not sure if you still need this, but for anyone else who needs this. 

The library exposes a static property with all the instance

https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L350

You can use this to search for the instance

```js
// Preferably do not extend the class statically
// but for the sake of the example
Awesomplete.getInstance = element => {
    return Awesomplete.all.find(instance => instance.input === element));
}
```

Hope it helps.
