### ISSUE TITLE
Add remove() api to destroy Awesomplete on element

### ISSUE THREAD

**Issue by CaitlinWeb** [LeaVerou/awesomplete#17037]
I used this in a project recently and found it to be easy to use and to customize for my purposes. Thanks!

However, I don't see a way to remove Awesomplete from the element. Something like destroy() or remove() should be available. It would remove all the markup generated by Awesomplete as well as Awesomplete's events.

This would be great for SPAs and for memory control purposes.

**Comment by LeaVerou** [comment]
I would merge a PR for this. I'd rather call it `destroy()`, which is more consistent with the naming of such functions in other libraries.

**Comment by dhritzkiv** [comment]
This would be great to have as it would also help deal with Awesomplete memory leaks: `_.all` is populated with each Awesomplete instance, but is never cleared of the instance, causing references to build up.

`.destroy()`/`.remove()` should also take care to clean `_.all` of the instance.

I might submit a PR, if I find some time to grok the source

**Comment by LeaVerou** [comment]
> I might submit a PR, if I find some time to grok the source

Looking forward to it!
