### ISSUE TITLE
No documentation or examples for listening to events

### ISSUE THREAD

**Issue by jpodpro** [LeaVerou/awesomplete#17034]
I had to search through random issues to figure out how to listen to events. Here is an example for anyone else:

```
Awesomplete.$.bind(document.getElementById('YOUR-INPUT-ID'), { "awesomplete-select":function(event)
{
    console.log( event.text.label, event.text.value );
}});
```

**Comment by LeaVerou** [comment]
`Awesomplete.$.bind` is just a small utility for attaching multiple event listeners. For a case like this, normal JS `addEventListener` should work just fine and is more readable:

```js
document.getElementById('YOUR-INPUT-ID').addEventListener("awesomplete-select", function(event) {
    console.log( event.text.label, event.text.value );
});
```

**Comment by ibnYusrat** [comment]
I was attempting to put the listener on the awsomeplete object itself. This definitely needs some mentioning on the main page imho.

**Comment by LeaVerou** [comment]
> I was attempting to put the listener on the awsomeplete object itself. This definitely needs some mentioning on the main page imho.

Pull request?

**Comment by eliasgonzalezugalde** [comment]
In regular Javascript

var input = document.getElementById("inputlist"); 
new Awesomplete(input, {list: yourlist});
document.getElementById('inputlist').addEventListener('awesomplete-selectcomplete',function(){
  alert(this.value); 
}); 

In Jquery

var input=$("#inputlist")[0];
new Awesomplete(input, {list: yourlist});
$("#inputlist").on('awesomplete-selectcomplete',function(){
  alert(this.value);
});

Source: http://stackoverflow.com/questions/35864545/awesomplete-get-selected-text

**Comment by ibnYusrat** [comment]
> Pull request?

Actually the readme on github is not as detailed as the one your website. That is the one which needs the update. If some writes about event listening on this readme, it will only confuse the readers because the rest of the page doesn't talk about any interaction with JavaScript.

**Comment by isapir** [comment]
@eliasgonzalezugalde Any idea on how to get the value passed into the event handlers in jQuery?  e.g. `awesomplete-close` event handler receives a `reason` argument, but how can I access that in a jQuery event handler?

**Comment by isapir** [comment]
@eliasgonzalezugalde It's ok, I figured it out, thanks.  Posting for benefit of others:


    $("#dropdown-search").on("awesomplete-close", function(e){
      console.log("reason", e.originalEvent.reason);
    });

**Comment by aagentah** [comment]
This seems bizarre that the events are bound to the target element rather than the Awesomplete instance?
