### ISSUE TITLE
Unable to disable sorting

### ISSUE THREAD

**Issue by jpodpro** [LeaVerou/awesomplete#17035]
The unflexibility of this plugin leaves much to be desired. I have my data items ordered in a particular way and do not want them re-ordered when the dropdown is opened. However there appears to be no way to disable sorting.

**Comment by LeaVerou** [comment]
Passing `function(){}` as the sort function doesn't work?

**Comment by davidkna** [comment]
@LeaVerou depends if `Array.prototype.sort` is stable in the given browser. (also: duplicate of #16771)

**Comment by evenfrost** [comment]
@LeaVerou Passing empty function does not work, only removing [this line](https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L250) helps.

**Comment by vlazar** [comment]
Closing since `sort: false` was introduced by #17043
