### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setAttribute' of null in 2017

### ISSUE THREAD

**Issue by BenSloboda** [LeaVerou/awesomplete#17042]
This is an old issue, but I've not seen a resolution (or found one I understand, perhaps).

I have a very simple page using the examples from the website that looks like this:

```
<!DOCTYPE html>
<html>
<!--Made with the Awesomplete plugin from Lea Verou http://lea.verou.me/-->
<head>
    <title>All Games List</title>
<link rel="stylesheet" href="https://leaverou.github.io/awesomplete/awesomplete.css" /> 
<script src="https://leaverou.github.io/awesomplete/awesomplete.js"></script> 
<script>
var input = document.getElementById("myinput");
var newlist = ["Ada", "Java", "JavaScript", "COBOL", "LOLCODE", "Node.js", "Ruby on Rails"];
new Awesomplete(input, {list: newlist});
</script>
</head>

<body>
<p> To use, just type the first two letters of the language name (or more if you want).</p>
<form>
        Language Name: <input id="myinput"/>
</form>
		
</body>
</html>
```

![image](https://cloud.githubusercontent.com/assets/7003845/22218182/024b5198-e163-11e6-9fc0-ac35f49b4256.png)

I still get the Uncaught error, and I don't know how to fix it.  I've tried from localhost and publishing to a webserver with no luck.  I've also tried with using the exact example code from the website without any luck.  I also tried Firefox, Chrome, and IE to no avail.  How do we set a value for the property so it isn't null on load (as I imagine hosting the library on my own server and this as a workaround)?  It seems to only happen with the new Awesomplete call, as I can easily use the datalist still.  However, I want to be able to add items to the array so the list can continue to grow.  Any help, please?

I'm sure it's something super simple, right?

-Ben (I'm new here)

**Comment by LeaVerou** [comment]
This is not an Awesomplete bug, but a result of how the DOM works. :)
You are running your code before the DOM is created, so there is no element with an id of "myinput" at the time the code runs. You can easily verify this in the console, by typing `console.log(myinput)` in your code and checking the console output.

There are two ways to fix this:
1. Put your code immediately before `</body>`
2. Wrap your code with an event listener that runs on DOMContentLoaded, like so:
```js
document.addEventListener("DOMContentLoaded", function() {
// code here
});
```

Also check out the pure HTML examples. You don't need to write JS to use Awesomplete if you're not comfortable with it. Having most functionality available via HTML is one of our main design principles.

Hope this helps, good luck!

**Comment by BenSloboda** [comment]
This makes perfect sense.  If I move it below the </body> tag, it will load after the DOM has a value in the myinput box.  If I create a listener, it won't fire the function until after the DOM has loaded.  This is the exact answer I was looking for.  Thank you so very much.  I really appreciate it.

-Ben

**Comment by xcel24** [comment]
I am also getting the same issue and I have checked that first my elements are created then I accessed them but still I am getting same error please help.
here's my code.


<html>
<head>
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
<link rel="stylesheet" type="text/css" href="https://rawgit.com/LeaVerou/awesomplete/gh-pages/awesomplete.css" />
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="http://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" ></script>
</head>
<body>
<table id="example" cellspacing="0" style="width:100%">
   <thead>
      <tr>
         <th>Name</th>
         <th>Position</th>
         <th>Office</th>
         <th>Age</th>
         <th>Start date</th>
         <th>Salary</th>
		 
      </tr>
   </thead>
   <tbody>
      <tr id="somerow">
         <td>Tiger Nixon</td>
         <td>System Architect</td>
         <td>Edinburgh</td>
         <td>61</td>
         <td>2011/04/25</td>
         <td id="Prateek" >$320,800</td>
		 
		 
		  
      </tr>
      <tr>
         <td>Garrett Winters</td>
         <td>Accountant</td>
         <td>Tokyo</td>
         <td>63</td>
         <td>2011/07/25</td>
         <td>$170,750</td>
      </tr>
      <tr>
         <td>Ashton Cox</td>
         <td>Junior Technical Author</td>
         <td>San Francisco</td>
         <td>66</td>
         <td>2009/01/12</td>
         <td>$86,000</td>
		 
      </tr>
      <tr>
         <td>Cedric Kelly</td>
         <td>Senior Javascript Developer</td>
         <td>Edinburgh</td>
         <td>22</td>
         <td>2012/03/29</td>
         <td>$433,060</td>
		 
      </tr>
      <tr>
         <td>Airi Satou</td>
         <td>Accountant</td>
         <td>Tokyo</td>
         <td>33</td>
         <td>2008/11/28</td>
         <td>$162,700</td>
		 
      </tr>
 
      
      
      
   </tbody>
   
</table>

<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"> </script>
<script type="text/javascript">
$(document).ready(function(){
$('#example').DataTable();
});
</script>

<script>
$(document).ready( function () {

    $('#example').DataTable();
var count=0;
$('#example thead').find('tr').append("<th>Tag </th>")
	$('#example').on( 'page.dt', function () {
   setTimeout(function(){
   if(count<1){
   appendInputs();
   }
    console.log(count)
	count++;
   })
   
   console.log('i am here')
  
} );

appendInputs()
})
function appendInputs(){
var table = document.getElementById("example");
$('#example tbody').find('tr').each(function(index){
console.log($(this).append('<input class="awesomplete" type="text" id="myinput'+index+'" data-list="Ada,Java,JavaScript,Brainfuck,LOLCODE,Node.js,Ruby on Rails"/>'))
console.log("myinput"+index);
})
}
</script>

<script type="text/javascript" src="https://cdn.rawgit.com/LeaVerou/awesomplete/gh-pages/awesomplete.min.js"></script>
<script type="text/javascript">
var data = document.getElementById("myinput4");
 var awesomplete = new Awesomplete(data, {
	minChars:1
});

setTimeout(function(){
		
		awesomplete.list=["Python","C","C++"];
		awesomplete.evaluate();
		},3000); 

</script>
</body>


</html>

**Comment by bhoreanna** [comment]
please help me this code is not working. When Dom is Loaded I did't get   console.log('DOM IS LOADED SUCESSFULLY');

document.addEventListener("DOMContentLoaded", function() {
  console.log('-------------------------------------');
  console.log('DOM IS LOADED SUCESSFULLY');

  console.log('iFrame',iFrame);
    iFrame[0].setAttribute("src", this.pdf);

  //iFrame.setAttribute("src","assets/anna.jpg");
  });
