### ISSUE TITLE
CSS TD scope conflicts

### ISSUE THREAD

**Issue by alocalsewerhistorian** [LeaVerou/awesomplete#17107]
awesomecomplete.css approx. line 110

td{
	/*  note... this overrides others 
	height: 100%; 
	*/
}

maybe change scoping with something like .awesomecomplete class?
thanks!

**Comment by niorad** [comment]
Where exactly lies this code? I couldn't find it in the awesomplete.css.

**Comment by alocalsewerhistorian** [comment]
hmmm, yes, I just rechecked, it was in some version I've downloaded right between .dropdown-input and  .dropdown-btn but it is not in the official zip or github versions. It appears to have come from some older version mixing style.css with awesomecomplete.css

Now I'm not sure where I got that version.
thanks so much for looking into this, sorry to have bothered you, I'll rebuild my apps with the correct version.
please close this request, 
thanks!
Greg

**Comment by alocalsewerhistorian** [comment]
thanks
