### ISSUE TITLE
Matching multiple words to same list item?

### ISSUE THREAD

**Issue by ahmedmohiduet** [LeaVerou/awesomplete#17109]
Can I match multiple words for same list-item?
Like I am typing employee id as well as name and same list item getting selected?

Let me know how can I accomplish this. Would like to implement one and PR

**Comment by stephenkeable** [comment]
The simplest fix might be to have the label of your items to be "name (id)" eg "Stephen (52)" and use the FILTER_CONTAINS filter option. Allowing it to match against either the name or the id number.

This will also ensure that the UI still has some highlighting to give the user feedback about what the search matched on.

**Comment by ahmedmohiduet** [comment]
aargh. couldn't come up with such elegant, brilliant and in fact the simplest idea 👍
