### ISSUE TITLE
pop up text color

### ISSUE THREAD

**Issue by robertnicjoo** [LeaVerou/awesomplete#17101]
Hi,

My select area text is same color as background is there a way that i can change it?

![untitled](https://user-images.githubusercontent.com/8672823/32923873-71c93906-cb6c-11e7-89c5-b55cb49d09bf.png)

**Comment by LeaVerou** [comment]
Just set a background on `.awesomplete > ul` via CSS :)

**Comment by robertnicjoo** [comment]
@LeaVerou I added **color** instead ;)

**Comment by LeaVerou** [comment]
A fine choice :)
