### ISSUE TITLE
Make it combo on click/touch

### ISSUE THREAD

**Issue by sakhdevel** [LeaVerou/awesomplete#17111]
Awesomplete helps to autocompete values, but I also need it to **show combobox on click**. So user can type in custom value with autocomplete or **choose from the same predefined values after clicking on input element**.

Can Awesomplete do this?

P.S.: I don't know how important next notice is but... Awesomplete is looking at "input" event to catch text changing. There is an old unresolved bug with IE 10-11. If some text input has not-empty placeholder, browser will trigger "input" event in the following cases:

- when input element is activated (placeholder is being hidden from element) 
- when page is loading or input element is blurred (placeholder is being shown in element)

This is the link to the bug https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/274987/

**Comment by sakhdevel** [comment]
This is how it may look. User clicked (or touched) left input box.
![image](https://user-images.githubusercontent.com/23290296/34750443-3a132e18-f5fb-11e7-86b6-7849bcad48bf.png)

**Comment by LeaVerou** [comment]
There is an example of this on the website: http://leaverou.github.io/awesomplete/#combobox

Regarding the PS, if you notice that this causes any issues in Awesomplete, please open a new bug about it!

**Comment by sakhdevel** [comment]
Hi! Thanks for your reply.
About the link http://leaverou.github.io/awesomplete/#combobox
Yes, this is appoximately how I solved the problem. I just wanted to know if I can do it something like this:
`new Awesomplete(inputReference, {
	comboOnClick: true,
	...
});`

or even

`new Awesomplete(inputReference, {
	comboOnClick: element,
	...
});`

**Comment by LeaVerou** [comment]
I’m not sure what you're trying to do. What do you want to happen on click? Click on which element(s)?

**Comment by sakhdevel** [comment]
[Awesomplete_combo_on_click_from_the_box.zip](https://github.com/LeaVerou/awesomplete/files/1664045/Awesomplete_combo_on_click_from_the_box.zip)

**Comment by sakhdevel** [comment]
When click on input box. I thought it wouldn't be bad to have this functionality from the box. When you browse site from mobile you don't want to input value, you want to choose it, but with possibility to input
