### ISSUE TITLE
Can I ignore specific characters?

### ISSUE THREAD

**Issue by ahmedmohiduet** [LeaVerou/awesomplete#17112]
I have a list of employees like:
EmployeeName [codeprefix-code]

I need to match 'codeprefix-code' and 'codeprefixcode' as well.
would like to ignore the '-'
would it be possible we can configure some ignore characters?

**Comment by LeaVerou** [comment]
Yes, just write a custom `filter` function! http://leaverou.github.io/awesomplete/#extensibility
