### ISSUE TITLE
Auto suggest not firing with dynamically added elements

### ISSUE THREAD

**Issue by ahmedmohiduet** [LeaVerou/awesomplete#17114]
I am adding html using javascript:
```
<input class="awesomplete"
       data-list="Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails" />
```
but it looks like typing on input not firing up auto suggestions

Do we need any additional method calls for making pop up work?

**Comment by niorad** [comment]
Are you getting any errors in the JS-Console of your Developer-Tools?

**Comment by ahmedmohiduet** [comment]
Nope. None I can see in my js console in my chrome

**Comment by ahmedmohiduet** [comment]
Nope. None I can see in my js console in my chrome. Although I can see some additional attributes in my working input elements like:
 `autocomplete="off" aria-owns="awesomplete_list_11" role="combobox"`

which do appear to be present in my newly added input element

I have just added this two atttributes:
class="awesomplete" and
       data-list="Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails"

**Comment by niorad** [comment]
Do you see activity in the devtool-DOM-tree as you type?
Did you add the awesomplete.css to your project?

**Comment by niorad** [comment]
If you add the Markup afterwards via JS, you'll have to initialize Awesomplete on the element, like
`var input = document.getElementById("myinput");
new Awesomplete(input, {list: document.querySelector("#mylist")});
`
See http://leaverou.github.io/awesomplete/

**Comment by ahmedmohiduet** [comment]
got it . let me check

**Comment by ahmedmohiduet** [comment]
Hi niorad! how can I listen to item select event?

**Comment by niorad** [comment]
See the website-section "Events". If the original issue is resolved, please close this ticket.
