### ISSUE TITLE
Awesomplete does not cleanup completely

### ISSUE THREAD

**Issue by ferencbeutel4711** [LeaVerou/awesomplete#17113]
Hi there,

I have noticed that after awesomplete is used, there is an element left at the bottom of the body which has the class 'visually-hidden'. Why is that? In my concrete case, it makes these elements visible, since your css is not loaded at all times on the page, the element persists however.

Thanks for looking into this.

**Comment by LeaVerou** [comment]
This looks related to the a11y PRs that have been merged a few months ago.
@mauriciosoares @stephenkeable @ginader worked on that part of the code, so ideally, one of them could address this issue?
It should be a simple fix, probably just removing the node after the Awesomplete is done.
@ferencbeutel could you please paste more details about that element? What does its source look like in the inspector?

**Comment by stephenkeable** [comment]
@ferencbeutel The element below that is visually-hidden, is a "status" which is used by screen readers, to give users that might be visually impaired additional information, such as the number of elements in the list. Or if they have not typed enough characters for the autocomplete to kick in yet.

In theory this could be shown to other users, although understand it's location would mean it would be hidden by the dropdown list possibly.

**Comment by ferencbeutel4711** [comment]
Hi there,

sorry for the late feedback.
To further clarify the issue, here is the obfuscated html of the element in question:

```html
<div class="custom_awesomplete" style="left: 608px; top: 415px;">
  <ul hidden="" style="width: 464px;">
    <li aria-selected="true"><span>option1</span></li>
    <li aria-selected="false"><span>option2</span></li>
    <li aria-selected="false"><span>option3</span></li>
  </ul>
  <span class="visually-hidden" role="status" aria-live="assertive" aria-relevant="additions">option1</span>
</div>
```

This div node is inserted at the very bottom of the body.
After the user interacted with Awesomplete, the ul list is invisible. However, the span is not hidden and visible. As I saw in your css, you are styling visually-hidden elements, however, your css is not loaded anymore after the interaction with Awesomplete is done. So it would be very much appreciated if awesomplete would remove itself completely from the dom after a user interacted with it.

**Comment by LeaVerou** [comment]
@stephenkeable My impression is that the status is retained in the DOM after Awesomplete is done.
I'm not an a11y expert, but I believe it's not needed anymore at that point?

**Comment by stephenkeable** [comment]
Ah ok, think I understand fully now. After a user has made a choice it would announce which item was selected. After that it could be removed for sure, as would be added back on a new init of Awesomplete.

@LeaVerou would I be right in thinking I need to modify the destroy method, to ensure that the extra aria/a11y elements are removed? Happy to do the work just want to make sure I do the right thing :)

**Comment by LeaVerou** [comment]
@stephenkeable 

> Happy to do the work just want to make sure I do the right thing :)

Thanks!

> would I be right in thinking I need to modify the destroy method, to ensure that the extra aria/a11y elements are removed?

No, `destroy()` is never called by `Awesomplete` itself, it was added for third-party code because people needed it. Even if Awesomplete is closed, the instance isn't destroyed because it might open again in the future.
It’s the `close()` method you need to modify.

**Comment by stephenkeable** [comment]
Great will get sorted this weekend.

**Comment by stephenkeable** [comment]
Sorry for delay with PR.

**Comment by ferencbeutel4711** [comment]
Isnt this issue fixed? I think it is safe to close :)
