### ISSUE TITLE
SET VALUE OF ANOTHER INPUT

### ISSUE THREAD

**Issue by bukowa** [LeaVerou/awesomplete#17139]

**Comment by scarroll32** [comment]
Please close this issue, it's hurting my eyes.

**Comment by LeaVerou** [comment]
Yeah, you'll need to be polite if you expect help. Nobody here is your customer or your employee (and even if they were, that's still unacceptable). That's not how open source works.

**Comment by bukowa** [comment]
@LeaVerou unacceptable is the current state of html javascript and development time needed to setup simple things.

**Comment by LeaVerou** [comment]
Agreed! Why don't you make something simpler? You could also participate in standards discussions to improve the underlying technologies, both W3C, WHATWG and ECMA do their work on Github :)

**Comment by bukowa** [comment]
@LeaVerou i tried but i gave up its not possible with current community. i was banned by github trying to bring people together... nothing will change, there is only one way that is: more and more layers on top of other layers, beacuse each time you propose something new, a meme about "lets have another standard" raises. 
now only more and more products appear, even if t hey are open source they are mainly made for auto-promotion, html is from 93 but still bilion of javascript libraries build on top of it, i quit i have to take care of my mental health beacuse when coding in js it only gets worse. nothing towards your library, the world we live in suck, if (some) poeple could spend their time instead of creating another libraries, buying new houses and cars, but creating products  and things that really help other beings this world would be beatiful. now i am out to relax and tomorrow back to doing that, but without any fking dropdowns
