### ISSUE TITLE
Excellent work, one suggested addition

### ISSUE THREAD

**Issue by Kedsta** [LeaVerou/awesomplete#17132]
Nice little bit of business I assume awsomeplete works on a single field only? 

I am working on a standalone app and have been looking for some way to autopopulate an entire form from name to zip code in one stroke based on a linked CSV file. The idea is that you can import and link to a list of customers and then when you take an order you type in the customer number or name etc and it polls the CSV file and populates all fields at once.

I think this would be a nice addition to awesomeplete.

All the best

Kevin

**Comment by LeaVerou** [comment]
Hi Kevin,

You could listen to [awesomplete-selectcomplete](http://leaverou.github.io/awesomplete/#events), take the values, and insert them into the rest of the form. You would need to use separate labels and values [as described here](http://leaverou.github.io/awesomplete/#extensibility).

Hope this helps!

**Comment by Kedsta** [comment]
Thanks I'll give that a shot


Kevin 

    On Tuesday, April 10, 2018, 6:13:51 AM PDT, Lea Verou <notifications@github.com> wrote:  
 
 
Hi Kevin,

You could listen to awesomplete-selectcomplete, take the values, and insert them into the rest of the form. You would need to use separate labels and values as described here.

Hope this helps!
