### ISSUE TITLE
Highlight event does not work

### ISSUE THREAD

**Issue by Truemedia** [LeaVerou/awesomplete#17158]
Just found this library today and been great to use so far.

I just have one issue which I think is either a bug or wrong in the documentation. The highlight event doesn't trigger for me, but other events do.

The code I'm using is as follows:
```js
mounted: function() {
    new Awesomplete(this.$refs.input, {
      list: this.$refs.datalist
    });
    console.log(this.$refs.input);
    this.$refs.input.addEventListener('awesomplete-select', function() {
      console.log('this works');
    });
    this.$refs.input.addEventListener('awesomplete-highlight', function (e) {
      console.log('this does not');
    });
  },
```

**Comment by Truemedia** [comment]
Also as context that is a function from a vue viewmodel (this.$refs.input is my input element)

**Comment by LeaVerou** [comment]
[It should certainly trigger](https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L263).
Do you have an online testcase?

**Comment by Truemedia** [comment]
It’s part of a big stack of components for a private client site so I can’t disclose any live instances. But you should be able to recreate that example if you just test the inside of the function as a stand-alone example.

**Comment by Truemedia** [comment]
@LeaVerou Sorry I have what i was after working now. The issue was I misunderstood what the highlight event was actually responding to, I didn't realise it was activated only by the arrow keys and not the currently highlighted items (bit misleading name).

There is also some conflicts with using a library like Vue on top of it so my solution was just to work around the events that I can, and improvise everything else.

I will close the issue now.
