### ISSUE TITLE
How to trigger an event 'awesomplete-selectcomplete'?

### ISSUE THREAD

**Issue by 12evgen** [LeaVerou/awesomplete#17156]
How to trigger an event 'awesomplete-selectcomplete'? I tried to use method select(), but it did not work

**Comment by LeaVerou** [comment]
`.select()` should trigger it, but only if there is a selection, and `awesomplete-select` has not been cancelled (i.e. the selection is valid), as you can see [here](https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L287).

If you're just looking to trigger the event, of course you could always do something like `element.dispatchEvent(new Event("awesomplete-selectcomplete"))`.
If you're looking to trigger something in Awesomplete, also take a look in the [API](https://leaverou.github.io/awesomplete/#api).

Hope this helps!
