### ISSUE TITLE
distributing awesomplete in WordPress plugin

### ISSUE THREAD

**Issue by pbiron** [LeaVerou/awesomplete#17169]
If I distribute `awesomplete` in a WordPress plugin, do I need to distribute the entire package as retrieved through NPM (including what is in the `test` directory)?  Or can I distribute what the "run-time" parts of your NPM package?

**Comment by LeaVerou** [comment]
The only thing you must include is the license. Apart from that, you may include whatever files are useful for your plugin and no more!

Hope this helps, and we'd love to know about your plugin when/if you're ready to share!

**Comment by pbiron** [comment]
> The only thing you must include is the license. Apart from that, you may include whatever files are useful for your plugin and no more!

Great, thanx for the clarification.

> Hope this helps, and we'd love to know about your plugin when/if you're ready to share!

The plugin is nearing release in the https://wordpress.org/plugins/ repo.  When it is, I'll try to remember to return here and let you know.

**Comment by LeaVerou** [comment]
Thanks, looking forward to it!

If it's of interest, you can also send a PR to add a section to the website about plugins using Awesomplete and add yours first — it's long overdue :)
