### ISSUE TITLE
awesome does not work in popup model

### ISSUE THREAD

**Issue by hardikpatel043** [LeaVerou/awesomplete#17171]
awesome does not work in popup model

**Comment by LeaVerou** [comment]
🤔🤔🤔

You will need to use more words if you want me to have any shot at understanding what you’re saying!

**Comment by wimarbueno** [comment]
962
024
290
985
041
043
Cid

**Comment by LeaVerou** [comment]
I guess I should have been more specific about the words needed 😂

**Comment by julian-tr** [comment]
> awesome does not work in popup model

Works perfectly in popup modals for me. I'm using it successfully with [jqModal](https://github.com/briceburg/jqModal) for example. Must be your implementation, or something in whichever modal code you're using - impossible to know without any details.

**Comment by LeaVerou** [comment]
Closing this since the original bug report does not make sense and @julian-tr could not reproduce (an interpretation of) the issue.
