### ISSUE TITLE
Distinguish between click and enter selections

### ISSUE THREAD

**Issue by briandipalma** [LeaVerou/awesomplete#17179]
The event `"awesomplete-selectcomplete"` provides you with the selected option but it doesn't tell you the user action that triggered the selection. Could I create a PR that provided the underlying event?

Basically `keydown` would pass the `evt` value to `select`

`me.select(undefined, undefined, evt);` and `select` would pass that on

```
"awesomplete-selectcomplete", {
  evt: evt,
  text: suggestion
}
```

and similar for `click`. Would that be an acceptable change?

**Comment by LeaVerou** [comment]
I would call it `originalEvent`, but apart from that, sure (as long as the PR also documents it)!

**Comment by briandipalma** [comment]
Hi, is it possible to get this change released to npm?
