### ISSUE TITLE
Host assets with direct URL's

### ISSUE THREAD

**Issue by mcandre** [LeaVerou/awesomplete#17188]
Hi, I am interested in using your awesomplete framework for autocompletion. However, I don't see a public URL for integrating the JS assets into our Web applications with normal `<script src="...">` tags. Could the assets please be hosted directly?

Looks like the assets are currently bundled as ZIP files, which slow down the installation process.

**Comment by LeaVerou** [comment]
For quickly testing stuff out, you could link them from the Awesomplete website:

https://leaverou.github.io/awesomplete/awesomplete.js
https://leaverou.github.io/awesomplete/awesomplete.css
