### ISSUE TITLE
XSS Attacks on Awesomplete

### ISSUE THREAD

**Issue by RajasekarPR** [LeaVerou/awesomplete#17184]
I am getting XSS attacks when using this plugin. Can you provide the solution to this please.

**Comment by LeaVerou** [comment]
What makes you think there is a vulnerability in Awesomplete and not another part of your codebase?

**Comment by bbenjamin** [comment]
I'm going to make the judgement call to close this as there are no actionable details - just a report that XSS attacks are happening, and it's been a year since the request for more info.
