### ISSUE TITLE
Cannot use 'in' operator to search for 'label' in null

### ISSUE THREAD

**Issue by jjhi11** [LeaVerou/awesomplete#17185]
I get the error in the console once I start to enter characters in the input box. Below is the error syntax from the console.
awesomplete.js:394 Uncaught TypeError: Cannot use 'in' operator to search for 'label' in null
    at new Suggestion (awesomplete.js:394)
    at awesomplete.js:310
    at Array.map (<anonymous>)
    at _.evaluate (awesomplete.js:309)

It looks like the function is trying to search for labels and values but my array is just strings.

Any thoughts?

**Comment by ghost** [comment]
I experienced the same issue, until I found that in my array were present some ```null``` values.
Check about their presence. If so, clean your array from them, then retry. After that It should work correctly.

**Comment by jjhi11** [comment]
Thanks Luca I will check it out.

**Comment by jjhi11** [comment]
No null values. I did however get the array moved into a ul and added each item to the list. However each entry ran together into one giant string. The array is quite large, at 448 items.

**Comment by jjhi11** [comment]
nope im sorry, one null. fixed.  thanks Luca
