### ISSUE TITLE
Scrolling with arrow key, highlights next but quickly goes back to highlight first item

### ISSUE THREAD

**Issue by hkunz** [LeaVerou/awesomplete#17207]
Hi. First and foremost i would like to say that your component is friggin awesome! it saved me big time! So thank you soooo much! .... I have a weird issue though when i dynamically assign a list.

//this is how i initialise the component when the DOM is ready
thiz.search_item_input = new Awesomplete(document.getElementById("search_item_input"), {minChars:2,maxItems:10,autoFirst:true}); 

onAjaxSuccess(data, thiz) {
                //thiz.search_item_input.list = data.split("||");
                //also tried commenting out and just assigning a test list but still doesnt work correctly
                thiz.search_item_input.list = ["test-1", "test-2", "test-3"]
                thiz.search_item_input.evaluate(); //with or without this line is same behavior
}

I have autoFirst enabled. So always the first item gets selected (i.e. "test-1"). But when i press down key to scroll down to "test-2" it highlights it but quickly jumps back and highlights "test-1".

Any idea how i can fix this or any workarounds?

**Comment by hkunz** [comment]
:(

**Comment by hkunz** [comment]
no more support for awesomplete? :(

**Comment by LeaVerou** [comment]
> no more support for awesomplete? :(

I'm just busy. A reduced testcase would help. Please google how to make a reduced testcase and post one here. It's generally easier to get support (in any project!) if you provide one instead of just dumping your code in an issue. We don't have crystal balls.

**Comment by hkunz** [comment]
wow. just wow. im stunned by how arrogant ur response is. im not more interested in your help. thank you and have a nice day.
