### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by LukaszJaro** [LeaVerou/awesomplete#17205]
Hi,

I'm getting this error when using custom event:

awesomplete.min.js?ver=0.9.3.1571775329:2 Uncaught TypeError: Cannot read property 'value' of undefined
    at r.REPLACE [as replace] (awesomplete.min.js?ver=0.9.3.1571775329:2)
    at r.select (awesomplete.min.js?ver=0.9.3.1571775329:2)
    at HTMLInputElement.keydown (awesomplete.min.js?ver=0.9.3.1571775329:2)

I'm trying to trigger another event when a certain list item is clicked:
```
window.addEventListener("awesomplete-open", function(e){
// Execute a function when the user keys down
					all_results.addEventListener("keydown", function(e) {
					// "Enter" key on the keyboard
					if (e.which == 13 || e.keyCode == 13) {
						// Cancel the default action, if needed
						//e.preventDefault();
						// Trigger the button element with a click
						document.getElementById("searchsubmit").click();
  					}
				});
}, false);
```

Any ideas on the issue?

Thanks.

**Comment by LeaVerou** [comment]
Hi there,

Sorry you're running into this.
To investigate, I'd need a live testcase that reproduces the issue. Either a minimal website or a [codepen](https://codepen.io) would work.

**Comment by LukaszJaro** [comment]
Hi @LeaVerou,

Thanks for getting back, will get around to that, just trying to do something simple. I dynamically appended a li element using `parent.addEventListener("awesomplete-open", function(e){ ..` 

I then add this event listener to trigger a search:
```
parent.addEventListener("awesomplete-select", function(event) {
	document.getElementById("searchsubmit").click();
});
```

But I only want the dynamically appended li element to trigger a search, and not the other generated list item suggestions.
