### ISSUE TITLE
HTML Entities

### ISSUE THREAD

**Issue by Lewiscowles1986** [LeaVerou/awesomplete#17209]
I was working with this for a project, and one of the things I wanted to do was use HTML entities in some of my Labels. When rendering from a list with other elements I see the rendered HTML entity as I would expect in my Label. When rendering a solo label with a HTML Entity I see the raw text.

More details. When I have no text typed, and I activate the Awesomplete it shows an unrendered Awesomplete label (raw HTML entities like you'd see in a text-editor).

### Received

<img width="212" alt="Screenshot 2019-11-29 at 02 37 23" src="https://user-images.githubusercontent.com/2605791/69839862-3d668000-1251-11ea-91ce-ec050dd39db5.png">

### Desired (not including france, just the HTML entity)

<img width="212" alt="Screenshot 2019-11-29 at 02 37 34" src="https://user-images.githubusercontent.com/2605791/69839863-3d668000-1251-11ea-8174-77c1d5bdb790.png">

### Here's a CodePen

https://codepen.io/Lewiscowles1986/pen/PooMgXE?editors=1010

### Known workaround

The workaround so-far has just been to paste the character literal in.

### Background

This is also an example of Live AJAX listing which I know some people have asked for.

I'm unsure if it's the best pattern, and sure writing my own debounce and using native DOM would be more accessible to a wider group of people. It also really spams data.

**Comment by bbenjamin** [comment]
I noticed your Codepen was using Awesomplete 1.0.0. This was fixed with 2015's 1.1 release https://github.com/LeaVerou/awesomplete/commit/6a6c8c1ccc2a50bdfa78cd9d5526dbd8afc723fa#diff-0861bfe5a8e20a86e84f647fe9e26358
 Update to the current version, 1.1.15, and you won't have this issue. I was able to do this in the Codepen you provided. 

I believe this can be closed!

**Comment by Lewiscowles1986** [comment]
Thanks @bbenjamin :heart: I'm very sorry for that

**Comment by LeaVerou** [comment]
Hey @bbenjamin, thank you for helping people in issues! Would you like to be added as a contributor?

**Comment by bbenjamin** [comment]
Happy to help, you can definitely add me as a contributor @LeaVerou!

Some context: Awesomplete is currently my (and several others) preferred replacement for jQuery UI autocomplete in Drupal core. jQuery UI has reached end-of-life so it must be phased out and replaced. In particular, Awesomplete has the best accessibility of all the options evaluated. I figured I'd extend my appreciation for Awesomplete existing by helping out.

**Comment by LeaVerou** [comment]
Thank you for the context, and the willingness to help! I'm spread way too thin, so any help is **very** appreciated. Just sent the invitation!
