### ISSUE TITLE
Default behavior that the input can match anywhere in the string is not working in my case

### ISSUE THREAD

**Issue by jahlomp** [LeaVerou/awesomplete#42]
Looking at the two images below, It seems the search word has to be word for word matching exactly what is in the list or options. I thought the  default behavior was to that the input can match anywhere in the string.

![screenshot from 2015-02-21 10 35 31](https://cloud.githubusercontent.com/assets/4746511/6313794/6bb635b2-b9b5-11e4-8173-be5b0dabaa4e.png)

![screenshot from 2015-02-21 10 35 08](https://cloud.githubusercontent.com/assets/4746511/6313798/908a3eba-b9b5-11e4-81f0-d6f8db2e40d4.png)

**Comment by vlazar** [comment]
By default Awesomplete uses `Awesomplete.FILTER_CONTAINS` which matches anywhere in the string.

Checked this with the very first basic example and it works for me:

``` html
<input autofocus class="awesomplete" data-list="Former GM CEO warns Apple against making cars, Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails" />
```

It works for me both when I type **For** and **Apple**. In both cases I see **Former GM CEO warns Apple against making cars** in completer.

If you still have this issue, please reopen and provide reproducible example somewhere to check.
