### ISSUE TITLE
Non minified version errors

### ISSUE THREAD

**Issue by martinsotirov** [LeaVerou/awesomplete#5175]
The min version of the script works perfectly but as soon as I substitute the non-minified version, I get an error: `TypeError: undefined is not an object (evaluating 'this._list.length')` on line 242.

**Comment by coRz** [comment]
Cant reproduce / was fixed already.

**Comment by LeaVerou** [comment]
Cannot reproduce either. Which browser?

**Comment by martinsotirov** [comment]
I found the problem. I was instantiating Awesomplete manually but I also had a list property on my search input which was tripping up the non-minified version for some reason.
