### ISSUE TITLE
Report abuse: new users are created with spamming purposes (dedewalker9, cfsxflsf, rhdkfk, ... sblvp7249, ... others)

### ISSUE THREAD

**Issue by lgs** [LeaVerou/awesomplete#70]
I just opened a request to @GitHub for checking dedewalker9 user which looks nasty. 
I case I'm wrong let me know!

**Comment by joseluis** [comment]
Good idea, I've done the same. It's obvious is spam so no, you're not wrong.

**Comment by viktorstrate** [comment]
Me too

**Comment by arthurvr** [comment]
Opening  this issue wasn't a good idea. Trolls are only searching for attention, don't feed them. Reporting them to github is the only right thing to do.

**Comment by arthurvr** [comment]
@LeaVerou Also, block that user for now, it will prevent him from opening issues I believe.

**Comment by LeaVerou** [comment]
Wow, that has never happened before. I reported him and blocked him, and closed all his issues, but I don’t think Github lets you delete issues (or am I missing it?). Odd.

**Comment by LeaVerou** [comment]
Also, I don’t think there’s an issue of “feeding the troll” here, it’s clearly a spambot.

**Comment by arthurvr** [comment]
> don’t think Github lets you delete issues (or am I missing it?). Odd.

No, you can't delete issues, tho normally GitHub support does that.

**Comment by lgs** [comment]
This `cfsxflsf`user is somehow related to my request of yesterday to block `dedewalker9` user too. Just signaled to GitHub this new one too, 

... but we/github should find a more structured way to block that behaviour before it generate 160 spamming issues! 

I sound strange to me @GitHub has not a spam bots prediction algorithm on new user creation ...

Any idea ?

**Comment by DanyUP** [comment]
The next one is bada999 :(

**Comment by jordanlapointe** [comment]
`rhdkfk` is the latest offender. I've reported the account and will update if GitHub support responds with useful information.

https://github.com/LeaVerou/awesomplete/issues/created_by/rhdkfk

**Comment by arthurvr** [comment]
Github support deleted all issues :)

**Comment by LeaVerou** [comment]
There's so much spam, it's extremely annoying. I had 548 Github emails of which only around 20 were non-spam. WTF.

**Comment by viktorstrate** [comment]
How does big repos prevent that?

**Comment by lgs** [comment]
I suggest everyone is going to `Report new abuses` to @GitHub for this repository to link this thread in the Body as [issue #70](https://github.com/LeaVerou/awesomplete/issues/70).

@GitHub should improve user creation process with "spamming filter kind of" mechanism.

`Here my Report abuse: sblvp7249:`

Body of the message:
[LeaVerou/awesomplete](https://github.com/LeaVerou/awesomplete) has been targeted by abusive and reiterate users creation with the only pourpose to spam his watcher user list. Please have a look at following thread: [issue #70](https://github.com/LeaVerou/awesomplete/issues/70).

This should be stoped as soon as possible to avoid compromising the usability of @GitHub `Watch` button (service/function).

**Comment by lgs** [comment]
@viktorstrate    

I guess they simply have not been targeted yet, but not sure. Have a look [here](https://github.com/blog/1426-spam-spam-spam-spam) anyway.

Seriously,  that's not enough and I PERSONALLY just decided to flag `Not Watching` this repo. 

I let you imagine how much this could impact @GitHub usability and data mining, if other users will decide the same.

**Comment by LeaVerou** [comment]
:(

**Comment by arthurvr** [comment]
> How does big repos prevent that?

I don't know of any repos I work on (some quite big ones) that have been spammed out this hard. Mostly github's anti-spam system works like a charm :(

**Comment by Mithgol** [comment]
Six or seven notifications per minute is more than my inbox should handle.

I've just unwatched this repo.

**Comment by medikoo** [comment]
I watch many big repos, and it's the only one that has such problem with spam. Weird that github is not able to stop it somehow.

**Comment by LeaVerou** [comment]
I think it might be related to the fact that it was trending in Github Explore. i.e. there are many big repos, but this one grew too fast and attracted the attention of spammers :(
I’ve never seen this before either. I get all notifications as emails and I have to clean up my inbox every day. Thankfully, I have Github emails going to a separate folder.

I don’t understand people like @Mithgol though, talking as if it’s somehow the fault of someone here. It’s not something we can control, no need to sound so disgruntled.

**Comment by joseluis** [comment]
I marked all those emails as spam, and then gmail started marking every incoming github email as spam :smile: 

I think @Mithgol was being practical. I thought of it too, but went for the adventure.

**Comment by lgs** [comment]
We need an answer by @GitHub ,,,,
unless they want to lose `watch` button functionality (and relative "social network data" ) !

**Comment by lgs** [comment]
@LeaVerou  

don't worry too much about what's happening here. 

Filtering a mailbox ourself or going back here by hand without receiving an email notification, is not a big deal and I'm doing it without any effort!

Moreover, this nice toy (- could be a bot-toy a digital version of a boy-toy !?! :-)
... its just rising [LeaVerou/awesomplete](https://github.com/LeaVerou/awesomplete) visibility ... and adoption at the end of the day !

The only failing here is social network credibility of GitHub (sorry to underline that but I care, really).

**Comment by lgs** [comment]
... hey, 

do you see what is happening here ? The pattern is changing on both side !

 ... I guess @GitHub "is filtering" quicker some how ...
and bot-toy is getting "smarter" ... :-)

**Comment by lgs** [comment]
@arthurvr       ... I start thinking u were right in this case too, as it ws for old BBS :(
> ... Trolls are only searching for attention, don't feed them ...

**Comment by ankush** [comment]
Another spammer - http://whatsappcalling.github.io/whatsappcalling/
He's using github pages for sh!tty surveys.
