### ISSUE TITLE
Default minimum number of chars before autocompletion in documentation differ from code

### ISSUE THREAD

**Issue by juanto121** [LeaVerou/awesomplete#72]
In code:

``` javascript
this.minChars = +input.getAttribute("data-minchars") || o.minChars || 2;
```

In Docs:
![minchars](https://cloud.githubusercontent.com/assets/4349047/6317818/bf0aa5e2-ba3a-11e4-853a-9d99737854d4.JPG)

**Comment by LeaVerou** [comment]
Oops. Anyone wants to send a PR to fix the docs?

**Comment by vlazar** [comment]
It's fixed.
