### ISSUE TITLE
bower install support?

### ISSUE THREAD

**Issue by iamnewton** [LeaVerou/awesomplete#786]
Not sure if this is something you were interested in, but I searched to see if awesomplete available as a bower module, and it wasn't.

**Comment by jaylinski** [comment]
+1

**Comment by LeaVerou** [comment]
Odd. I thought after merging #25 it would be…

**Comment by iamnewton** [comment]
My bad.  It is there, its just not registered with bower registry, and since there's not a master its not as easy to find.  Maybe in the README you can suggest installing with bower by running this:

```
bower install https://github.com/LeaVerou/awesomplete.git#gh-pages
```

Thanks for the awesome project.

**Comment by LeaVerou** [comment]
Sure! Pull request?

**Comment by iamnewton** [comment]
Done. #1032

**Comment by anselmh** [comment]
To make it work with Bower you could also provide git tags for the releases and increase the version in the `bower.json` file regardingly. Then it wouldn’t make a difference if `master` branch or `gh-pages` branch is used as primary branch.

**Comment by seanrucker** [comment]
Has there been any movement on this? Getting this library into an Ember app without bower support is a pain.

**Comment by vlazar** [comment]
Removed version in bower.json #16863

We will release 1.1 soon. Track progress here https://github.com/LeaVerou/awesomplete/milestones/v1.1
