### ISSUE TITLE
Cross-Browser Support

### ISSUE THREAD

**Issue by alishahab** [LeaVerou/awesomplete#837]
Please try to make it compatible with more then 1% usage browsers.

**Comment by ottuzzi** [comment]
Hi,

  does not work with ie8: this is a perfectly sensible choice but, please, add a list of supported browser in readme :)

Thanks
Bye
Piero

**Comment by vlazar** [comment]
-1
Please don't. Let's move the web forward :)

**Comment by LeaVerou** [comment]
If someone wants to investigate the IE9 issue, and submit a fix, I’d be willing to consider it (assuming the fix isn't too horrible or more than a couple loc). But IE8 is out of the question.
It’s not just market share that matters, it’s also the trend. IE8 usage is dropping, fast. And autocomplete in most cases is a nice-to-have, not something that breaks the website if it’s not there.

**Comment by drifterz28** [comment]
I know this is closed but I wanted to add that this works just fine in IE9 when the scripts are moved before the closing body tag or it is wrapped in an onload event.

**Comment by LeaVerou** [comment]
Hmm interesting, thanks @drifterz28! Pull request? :)

**Comment by vlazar** [comment]
Which probably means the code waiting for DOM ready fails in IE9?
https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L365-L372

@LeaVerou I could probably fix it if only we have tests first ;)
How about one of the test frameworks and test runners mentioned in https://github.com/LeaVerou/awesomplete/issues/14565
